### ISSUE TITLE
Please remember increasing versionCode

### ISSUE THREAD

**Issue by IzzySoft** [RohitKushvaha01/Xed-Editor#1]
Please remember to always [increase `versionCode`](https://github.com/RohitKushvaha01/Xed-Editor/blob/main/app/build.gradle.kts#L40) when preparing a new release, or your updates won't reach those having previous versions installed. Android uses this internally to keep versions apart – and if it's not changed considers the APK as "already installed" and ignores it.

    Binary files /web/ftp/repo/fdroid/repo/com.rk.xededitor_1.apk and /web/ftp/repo/fdroid/repo/com.rk.xededitor_1.0.3.apk differ

This means, the file was just **replaced** in my repo – but will still be shown as first and only release. Oh, and for F-Droid.org (where you applied for inclusion IIRC) it will mean it will never arrive there even, as their update checker will say "`versionCode: 1`? We already have that, so no need to build it."

**Comment by RohitKushvaha01** [comment]
> Please remember to always [increase `versionCode`](https://github.com/RohitKushvaha01/Xed-Editor/blob/main/app/build.gradle.kts#L40) when preparing a new release, or your updates won't reach those having previous versions installed. Android uses this internally to keep versions apart – and if it's not changed considers the APK as "already installed" and ignores it.
> 
> ```
> Binary files /web/ftp/repo/fdroid/repo/com.rk.xededitor_1.apk and /web/ftp/repo/fdroid/repo/com.rk.xededitor_1.0.3.apk differ
> ```
> 
> This means, the file was just **replaced** in my repo – but will still be shown as first and only release. Oh, and for F-Droid.org (where you applied for inclusion IIRC) it will mean it will never arrive there even, as their update checker will say "`versionCode: 1`? We already have that, so no need to build it."

Thanks for pointing out the problem I have updated versioncode just now in v1.0.4

**Comment by IzzySoft** [comment]
> Thanks for pointing out the problem I have updated versioncode just now in v1.0.4

Have you pushed the changes yet? Because I still see it set to `1` here in the repo. It also says 1.0.3 still here, so maybe it's not yet here?

**Comment by RohitKushvaha01** [comment]
> > Thanks for pointing out the problem I have updated versioncode just now in v1.0.4
> 
> Have you pushed the changes yet? Because I still see it set to `1` here in the repo. It also says 1.0.3 still here, so maybe it's not yet here?

I have have updated the app see the releases

**Comment by RohitKushvaha01** [comment]
> > Thanks for pointing out the problem I have updated versioncode just now in v1.0.4
> 
> Have you pushed the changes yet? Because I still see it set to `1` here in the repo. It also says 1.0.3 still here, so maybe it's not yet here?

I forgot to push the repo and just released the build 😅 let me push it

**Comment by RohitKushvaha01** [comment]
> > Thanks for pointing out the problem I have updated versioncode just now in v1.0.4
> 
> Have you pushed the changes yet? Because I still see it set to `1` here in the repo. It also says 1.0.3 still here, so maybe it's not yet here?

I have pushed the repo do I have to create the release again? Because I added the release apk before pushing

**Comment by IzzySoft** [comment]
All fine now, thanks! And no need to create the release again this time. Just remember for next time that the tag should point to the commit where you've built the APK from – which of course requires that commit to be pushed :wink:

**Comment by RohitKushvaha01** [comment]
> All fine now, thanks! And no need to create the release again this time. Just remember for next time that the tag should point to the commit where you've built the APK from – which of course requires that commit to be pushed 😉

What do you mean by "point to the commit"?
Currently I just put version name in the tag

**Comment by IzzySoft** [comment]
![image](https://github.com/RohitKushvaha01/Xed-Editor/assets/6781438/4ecad2c1-4bc4-4aad-a0c4-7c0b6af9fe6c)

See on the left-hand side, under your name is the tag name. Under the tag name is the commit you've tagged, here 460f856 – which is where you changed `versionName` from "1.0.2" to "1.0.3" – so it is not the commit marking the code v1.0.4 was built from – which most likely was c1b2ac3

So in other words, assuming you prepare everything on your local machine, the following workflow would produce the desired results:

* make the final commit for the release, i.e. the one where `versionName` and `versionCode` are adjusted
* build the APK based on that commit
* tag (locally, on your machine)
* push commits including tags (`git push --tags`)
* now, at Github, create your release based on that tag, and attach the APK to it.
