### ISSUE TITLE
word wrap spillover

### ISSUE THREAD

**Issue by risky777** [RohitKushvaha01/Xed-Editor#11]
Thanks for word-wrap. But it has bug. On writing, edge of screen is not properly detected so several letters on end of line are not shown since they are out of screen.

Anyway, word-wrap enabled me for testing, so I see that you still have basic issues, like following:
- after minimize-maximize app, open text file is not shown
- on exit, there is no message about unsaved changes

**Comment by RohitKushvaha01** [comment]
Thanks for feedback i will try to fix them asap

**Comment by risky777** [comment]
Problem is still there in version 1.1.9.

I'll try to explain. If I write word "editor" at end of line:
- part "ed" will be visible at end of line
- part "itor" will be outside of screen (not visible)
- next word will be in next line

It seem like xed has problem detecting screen size.

**Comment by RohitKushvaha01** [comment]
> Problem is still there in version 1.1.9.
> 
> I'll try to explain. If I write word "editor" at end of line:
> - part "ed" will be visible at end of line
> - part "itor" will be outside of screen (not visible)
> - next word will be in next line
> 
> It seem like xed has problem detecting screen size.

Can you send a screenshot?

**Comment by RohitKushvaha01** [comment]
> Problem is still there in version 1.1.9.
> 
> I'll try to explain. If I write word "editor" at end of line:
> 
>     * part "ed" will be visible at end of line
> 
>     * part "itor" will be outside of screen (not visible)
> 
>     * next word will be in next line
> 
> 
> It seem like xed has problem detecting screen size.

actually its not a bug you described only happens when you open a very large file the bigger the file is the longer it will take the word wrap to wrap the words
