### ISSUE TITLE
Bug when open termux folder 

### ISSUE THREAD

**Issue by Samuel689c** [RohitKushvaha01/Xed-Editor#111]
Fatal Crash occurred on Thread named 'Thread-9'
Unix Time : 1725220598819
LocalTime : 1 Sep 2024 23:26:38

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = SM-A125F
SEM_INT = 3001
SECURITY_PATCH = 2023-01-01
BASE_OS = samsung/a125f/a12:11/RP1A.207720.022/A125FXXU2CWB5:user/release-keys
SEM_FIRST_SDK_INT = 28
RELEASE = 11
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 11
SDK_INT = 30
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 30
SEM_PLATFORM_INT = 120100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = A125FXXU2CWB5

```
Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:923)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-9'
> Unix Time : 1725220598819
> LocalTime : 1 Sep 2024 23:26:38
> 
> ACTIVE_CODENAMES = []
> app_version = 2.6.0
> device_model = SM-A125F
> SEM_INT = 3001
> SECURITY_PATCH = 2023-01-01
> BASE_OS = samsung/a125f/a12:11/RP1A.207720.022/A125FXXU2CWB5:user/release-keys
> SEM_FIRST_SDK_INT = 28
> RELEASE = 11
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 11
> SDK_INT = 30
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 30
> SEM_PLATFORM_INT = 120100
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = A125FXXU2CWB5
> 
> ```
> Error Message : listFiles(...) must not be null
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException: listFiles(...) must not be null
> 	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at java.lang.Thread.run(Thread.java:923)
> 
> 

This issue is already fixed in commit builds you can download latest pre release APK from GitHub actions or wait for a new release
