### ISSUE TITLE
Unable to access storage in terminal proot distro

### ISSUE THREAD

**Issue by Brajesh3** [RohitKushvaha01/Xed-Editor#116]
Things gonna be good if we can access both device internal & external storage.
Don't know if it's possible to access external storage

Karbon
![Screenshot_20240903-231532_Karbon](https://github.com/user-attachments/assets/6868663e-ae3c-4769-9131-d8fb39feab9a)

Termux: in here we can access the internal storage
![Screenshot_20240903-230249_TermuxMonet](https://github.com/user-attachments/assets/fd7c115e-8d33-4266-9d97-013eebff13eb)

**Comment by AndroMaster436** [comment]
I have already reported @RohitKushvaha01 to this bug.

**Comment by Brajesh3** [comment]
I see, still i think having different issue apart from TODO is gonna be organized
