### ISSUE TITLE
Changing device theme closes all open documents

### ISSUE THREAD

**Issue by fredgolightly** [RohitKushvaha01/Xed-Editor#118]
**Describe the bug**
Changing device light/dark theme closes all open documents + opened folder/directory

**To Reproduce**
Change device theme from quick tile

**Expected behavior**
All open documents stay open

**Screenshots**
N/a

**complete the following information):**
Samsung Tab S8 Ultra, Tab S9 - Android 14
Pixel 8 Android 15

**Comment by AndroMaster436** [comment]
An option needs to be added so that the editor saves open files (so that they are reopened when launched)
