### ISSUE TITLE
[Feature Request] VIM Keybinds

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [RohitKushvaha01/Xed-Editor#12]
Like the title says, I would like to be able to use VIM keybinds to edit my text.
It's fine if this is implemented as a toggle in the settings, but what's the point of being an advanced and versatile text editor if you can't edit text using the VIM keybinds like a LOT of advanced Linux users do.

**Comment by RohitKushvaha01** [comment]
"Vim like keybindings", these are what comes into my mind.

  1.  navigate cursor via hjkl
  2. navigate pages via ctrl + d/u or ctrl + f/b
  3. gg to jump to top of the screen, G for the bottom
  
is this you want to be added?

**Comment by RohitKushvaha01** [comment]
> "Vim like keybindings", these are what comes into my mind.
> 
>   1.  navigate cursor via hjkl
>   2. navigate pages via ctrl + d/u or ctrl + f/b
>   3. gg to jump to top of the screen, G for the bottom
>   
> is this you want to be added?
>

**Comment by RohitKushvaha01** [comment]
> Like the title says, I would like to be able to use VIM keybinds to edit my text.
> It's fine if this is implemented as a toggle in the settings, but what's the point of being an advanced and versatile text editor if you can't edit text using the VIM keybinds like a LOT of advanced Linux users do.

"Vim like keybindings", these are what comes into my mind.

  1.  navigate cursor via hjkl
  2. navigate pages via ctrl + d/u or ctrl + f/b
  3. gg to jump to top of the screen, G for the bottom
  
is this you want to be added?

**Comment by LovecraftianGodsKiller** [comment]
Any chance all the VIM keybindings could be added?
Cuz I use VIM, specifically Neovim, religiously on all my systems.

**Comment by RohitKushvaha01** [comment]
> Any chance all the VIM keybindings could be added?
> Cuz I use VIM, specifically Neovim, religiously on all my systems.

I will add above keybinds I am working on a plugin system so it will be easy to add and customise such things
