### ISSUE TITLE
Disable 'Show Line Numbers' option not persistent

### ISSUE THREAD

**Issue by smaragdus** [RohitKushvaha01/Xed-Editor#120]
**Version**

2.6.0 (30) [F-Droid](https://f-droid.org/packages/com.rk.xededitor/)

**Bug**
After restarting the app line numbers still appear even rhough the option has been disabled.

**Reproduction**

- Open **Settings**;
- Go to **Editor**;
- Turn off **Show Line Numbers**;
- Exit **Karbon**;
- Restart **Karbon**;
- Line numbers reappear even though the option has been turned off;

In short, even  after **Show Line Numbers** option has been disabled, on app restart the line numbers appear again. So any time **Karbon** is started the user needs to enable and disable again this option to remove line numbers from editor.

**Comment by RohitKushvaha01** [comment]
> **Version**
> 
> 2.6.0 (30) [F-Droid](https://f-droid.org/packages/com.rk.xededitor/)
> 
> **Bug**
> Aftet restarting the app line numbers still appear even rhough the option has been disabled.
> 
> **Reproduction**
> 
> - Open **Settings**;
> - Go to **Editor**;
> - Turn off **Show Line Numbers**;
> - Exit **Karbon**;
> - Restart **Karbon**;
> - Line numbers reappear even though the option has been turned off;
> 
> In short, even  after **Show Line Numbers** option has been disabled, on app restart the line numbers appear again. So any time **Karbon** is started the user needs to enable and disable again this option to remove line numbers from editor.

This issue is already fixed in version 2.7.0, it just not released yet

**Comment by smaragdus** [comment]
@RohitKushvaha01 
Very fast response, thanks.
