### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cosmicdemopop** [RohitKushvaha01/Xed-Editor#128]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1725890061485
LocalTime : 9 Sept 2024 3:54:21 pm

# ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = WDY-LX2
SECURITY_PATCH = 2024-07-01
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = HONOR
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = HONOR
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 8.0.0.151C185E1R2P3

Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
Error Cause : java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
Error StackTrace : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4610)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:118)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:153)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:104)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3067)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9652)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
	at com.rk.xededitor.setupEditor.setupLanguage(Unknown Source:2)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.java:237)
	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.java:117)
	at android.app.Activity.performCreate(Activity.java:9032)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4592)
	... 12 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1725890061485
> LocalTime : 9 Sept 2024 3:54:21 pm
> 
> # ACTIVE_CODENAMES = []
> app_version = 2.6.0
> device_model = WDY-LX2
> SECURITY_PATCH = 2024-07-01
> BASE_OS = 
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = HONOR
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> brand = HONOR
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 8.0.0.151C185E1R2P3
> 
> 
> Error Message : Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
> Error Cause : java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rk.xededitor/com.rk.xededitor.SimpleEditor.SimpleEditor}: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4610)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4806)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:118)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:153)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:104)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3067)
> 	at android.os.Handler.dispatchMessage(Handler.java:117)
> 	at android.os.Looper.loopOnce(Looper.java:210)
> 	at android.os.Looper.loop(Looper.java:302)
> 	at android.app.ActivityThread.main(ActivityThread.java:9652)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
> Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.rk.xededitor.setupEditor.setupLanguage, parameter fileName
> 	at com.rk.xededitor.setupEditor.setupLanguage(Unknown Source:2)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.handleIntent(SimpleEditor.java:237)
> 	at com.rk.xededitor.SimpleEditor.SimpleEditor.onCreate(SimpleEditor.java:117)
> 	at android.app.Activity.performCreate(Activity.java:9032)
> 	at android.app.Activity.performCreate(Activity.java:8991)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4592)
> 	... 12 more
> 

You are using a very old version, please install new version from github actions or wait for next release
