### ISSUE TITLE
Unable to access SAF 

### ISSUE THREAD

**Issue by Brajesh3** [RohitKushvaha01/Xed-Editor#131]
**Describe the bug**
Can't access termux internal folder from SAF

**To Reproduce**
1. Open Karbon
2. Click on + button
3. Choose any SAF `termux home`
4. You see a question mark with home
5. When click on home it opens in editor

**Expected behavior**
Should able to acces the files & directories easily

**Screenshots**
![Screenshot_20240910-010229_Files](https://github.com/user-attachments/assets/172995a8-d10c-436b-9f5e-76786a968cdd)
![Screenshot_20240910-010215_Karbon](https://github.com/user-attachments/assets/ca7af36f-221f-4972-b977-99d995329b24)
![Screenshot_20240910-010527_Karbon](https://github.com/user-attachments/assets/078f634a-e8a6-4757-a16c-2d31f7cb9c8f)

**complete the following information):**
 - Device: samsung Galaxy M11
 - OS: [One UI]
 - Android Version [Android 12]
 - arch [arm32]
 - ram/storage [4gb/64gb]

**logcat output/logcat.txt(if applicable)**

**Additional context**

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> Can't access termux internal folder from SAF
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Open Karbon
> 2. Click on + button
> 3. Choose any SAF `termux home`
> 4. You see a question mark with home
> 5. When click on home it opens in editor
> 
> **Expected behavior**
> Should able to acces the files & directories easily
> 
> **Screenshots**
> ![Screenshot_20240910-010229_Files](https://github.com/user-attachments/assets/172995a8-d10c-436b-9f5e-76786a968cdd)
> ![Screenshot_20240910-010215_Karbon](https://github.com/user-attachments/assets/ca7af36f-221f-4972-b977-99d995329b24)
> ![Screenshot_20240910-010527_Karbon](https://github.com/user-attachments/assets/078f634a-e8a6-4757-a16c-2d31f7cb9c8f)
> 
> 
> **complete the following information):**
>  - Device: samsung Galaxy M11
>  - OS: [One UI]
>  - Android Version [Android 12]
>  - arch [arm32]
>  - ram/storage [4gb/64gb]
> 
> **logcat output/logcat.txt(if applicable)**
> 
> 
> **Additional context**
> Add any other context about the problem here.
> 

Karbon access files using native Linux paths. However, Termux provides a URI for its home directory, which cannot be directly converted into a native Linux path. Even if Karbon could convert this URI, Android would still deny access due to its permission model. In short, Termux files can't be accessed by Karbon without root permission.
