### ISSUE TITLE
Open last used folder

### ISSUE THREAD

**Issue by nuttintoseehere** [RohitKushvaha01/Xed-Editor#14]
Would it be possible to get a toggle for remembering the last used file (or preferably folder) on app launch? This app is also useful for managing simple notes stored in txt files, but having to always navigate to the files i want seems a hassle.

Currently, if i open a folder, all the notes appear correctly in the side drawer but they are forgotten the next time i launch the app.

Also, unless "legacy file browser" is enabled, i get a toast "onitemclick" when selecting a file from the drawer. Running GrapheneOS, based on Android 14. With the legacy browser enabled i can open them, but they are no longer in alphabetical order.

**Comment by RohitKushvaha01** [comment]
> Would it be possible to get a toggle for remembering the last used file (or preferably folder) on app launch? This app is also useful for managing simple notes stored in txt files, but having to always navigate to the files i want seems a hassle.
> 
> Currently, if i open a folder, all the notes appear correctly in the side drawer but they are forgotten the next time i launch the app.
> 
> Also, unless "legacy file browser" is enabled, i get a toast "onitemclick" when selecting a file from the drawer. Running GrapheneOS, based on Android 14. With the legacy browser enabled i can open them, but they are no longer in alphabetical order.

I am working on a better way of browsing files and the toast is for debugging purposes and will be removed in next release 

currently the new one is buggy so try not to use it for now

 I will add file remebering feature in next release

**Comment by octvs** [comment]
There were couple of releases since this discussion. Is this feature implemented? Would be nice to able to start with the last file.

**Comment by RohitKushvaha01** [comment]
> There were couple of releases since this discussion. Is this feature implemented? Would be nice to able to start with the last file.


Remembering of last file is not implemented but last directory is remembered
