### ISSUE TITLE
Minor bugs and requests

### ISSUE THREAD

**Issue by sofia-gros** [RohitKushvaha01/Xed-Editor#146]
5. automatic indentation needs to be improved. 
> The indentation needs to be lowered when closing.

6. when writing Html tags, "<>" becomes "<>>" when writing "<>".
> Other Editors, such as VSCode, do not allow ">" user input after generating closing brackets.

The part of 5 and 6
```html
<html>
  <head> 
    </head>        <!- High indent -->
  <body>
    <>>         <!- "<" is not through and hard to write -->
    </body>
      </html>
```

Using a DeepL translate

**Comment by AndroMaster436** [comment]
> 1. tab size is not reflected in the editor after changing the tab size in Settings -> Tab Size.
> 2. the TAB and UNTAB keys do not work. Or when UNTAB is pressed, one character is deleted.
> 3. when I press SETTINGS or move to another scene, the opened files and folders are closed by themselves.
> 4. after the background task is closed, when I go back to the application again, it does not return to the screen before closing.
> 
> > 3, 4 should save the state of the scene.
> 
> 5. automatic indentation needs to be improved.
> 
> > The indentation needs to be lowered when closing.
> 
> 6. when writing Html tags, "<>" becomes "<>>" when writing "<>".
> 
> > Other Editors, such as VSCode, do not allow ">" user input after generating closing brackets.
> 
> The part of 5 and 6
> 
> ```
> <html>
>   <head> 
>     </head>        <!- High indent -->
>   <body>
>     <>>         <!- "<" is not through and hard to write -->
>     </body>
>       </html>
> ```
> 
> Using a DeepL translate

Regarding point 5, the same thing happens with brackets and quotation marks in other languages.

**Comment by sofia-gros** [comment]
Others found.

1. cannot type in terminal with 2-byte language keyboard app.
> I expected it to be the 2-byte part because I could not type English on my Japanese keyboard.

2. when I switch keyboard input apps with terminal open, the keyboard does not appear because the forcus has not been unlocked once.

3. because of problems 1 and 2, Exit cannot be entered, so it is not possible to move from the terminal screen.
> Enable to exit terminal using Android's standard back button (e.g. press it twice if you want to avoid misfires).

**Comment by RohitKushvaha01** [comment]
> Others found.
> 
> 1. cannot type in terminal with 2-byte language keyboard app.
> > I expected it to be the 2-byte part because I could not type English on my Japanese keyboard.
> 
> 2. when I switch keyboard input apps with terminal open, the keyboard does not appear because the forcus has not been unlocked once.
> 
> 3. because of problems 1 and 2, Exit cannot be entered, so it is not possible to move from the terminal screen.
> > Enable to exit terminal using Android's standard back button (e.g. press it twice if you want to avoid misfires).

Assuming you are not using v2.6.0 
Terminal allows exiting by pressing back button twice

**Comment by RohitKushvaha01** [comment]
> Others found.
> 
> 2. when I switch keyboard input apps with terminal open, the keyboard does not appear because the forcus has not been unlocked once.
> 
> 3. because of problems 1 and 2, Exit cannot be entered, so it is not possible to move from the terminal screen.
> > Enable to exit terminal using Android's standard back button (e.g. press it twice if you want to avoid misfires).
