### ISSUE TITLE
Crash Report: clicking on settings > application > themes

### ISSUE THREAD

**Issue by Brajesh3** [RohitKushvaha01/Xed-Editor#151]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1727151916374
LocalTime : 24 Sept 2024 09:55:16

ACTIVE_CODENAMES = []
app_version = 2.7.2
device_model = SM-M115F
SEM_INT = 3101
SECURITY_PATCH = 2023-11-01
BASE_OS = samsung/m11qnnxx/m11q:12/SP1A.210812.016/M115FXXU5CWE3:user/release-keys
SEM_FIRST_SDK_INT = 29
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
SEM_PLATFORM_INT = 130100
brand = samsung
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = M115FXXS5CWK3

Error Message : Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
	at y3.e.b(Unknown Source:256)
	at D3.i.onClick(Unknown Source:69)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1727151916374
> LocalTime : 24 Sept 2024 09:55:16
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.2
> device_model = SM-M115F
> SEM_INT = 3101
> SECURITY_PATCH = 2023-11-01
> BASE_OS = samsung/m11qnnxx/m11q:12/SP1A.210812.016/M115FXXU5CWE3:user/release-keys
> SEM_FIRST_SDK_INT = 29
> RELEASE = 12
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 12
> SDK_INT = 31
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 31
> SEM_PLATFORM_INT = 130100
> brand = samsung
> supported_abi = [armeabi-v7a,armeabi]
> INCREMENTAL = M115FXXS5CWK3
> 
> 
> Error Message : Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
> 	at y3.e.b(Unknown Source:256)
> 	at D3.i.onClick(Unknown Source:69)
> 	at android.view.View.performClick(View.java:7792)
> 	at android.view.View.performClickInternal(View.java:7769)
> 	at android.view.View.access$3800(View.java:910)
> 	at android.view.View$PerformClick.run(View.java:30218)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8751)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
> 

Try now with new commit
