### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NikhilTomar3000** [RohitKushvaha01/Xed-Editor#165]
Fatal Crash occurred on Thread named 'main'
Unix Time : 1727597421285
LocalTime : 29-Sept-2024 13:40:21

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = RMX3521
SECURITY_PATCH = 2024-07-05
BASE_OS = 
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = realme
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
brand = realme
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = S.1907276_385d-46632

Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
Error Cause : kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
Error StackTrace : 

java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5984)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6022)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
	at com.rk.xededitor.terminal.Terminal.getTerminal(Terminal.kt:29)
	at com.rk.xededitor.terminal.Terminal.onDestroy(Terminal.kt:67)
	at android.app.Activity.performDestroy(Activity.java:9049)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1510)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5971)
	... 13 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1727597421285
> LocalTime : 29-Sept-2024 13:40:21
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = RMX3521
> SECURITY_PATCH = 2024-07-05
> BASE_OS = 
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = realme
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> brand = realme
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = S.1907276_385d-46632
> 
> 
> Error Message : Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> Error Cause : kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> Error StackTrace : 
> 
> java.lang.RuntimeException: Unable to destroy activity {com.rk.xededitor/com.rk.xededitor.terminal.Terminal}: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5984)
> 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6022)
> 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
> 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:257)
> 	at android.os.Looper.loop(Looper.java:368)
> 	at android.app.ActivityThread.main(ActivityThread.java:8839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Caused by: kotlin.UninitializedPropertyAccessException: lateinit property terminal has not been initialized
> 	at com.rk.xededitor.terminal.Terminal.getTerminal(Terminal.kt:29)
> 	at com.rk.xededitor.terminal.Terminal.onDestroy(Terminal.kt:67)
> 	at android.app.Activity.performDestroy(Activity.java:9049)
> 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1510)
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5971)
> 	... 13 more
> 

Bad internet connection
