### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Gitbobbit** [RohitKushvaha01/Xed-Editor#174]
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-2'
Unix Time : 1728072069354
LocalTime : Oct 4, 2024 4:01:09 PM

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = moto g stylus 5G
SECURITY_PATCH = 2023-06-01
BASE_OS = 
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = motorola
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
brand = motorola
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 5d8c81-392f6

Error Message : java.lang.String cannot be cast to java.lang.Boolean
Error Cause : null
Error StackTrace : 

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
	at com.rk.xededitor.App.onCreate$lambda$2(App.kt:45)
	at com.rk.xededitor.App.$r8$lambda$RirlTQxKpIxmHzKy_5qXCooNBmY(Unknown Source:0)
	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at com.rk.libcommons.After$1.invokeSuspend(After.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3f52c2a, Dispatchers.Default]

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-2'
> Unix Time : 1728072069354
> LocalTime : Oct 4, 2024 4:01:09 PM
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = moto g stylus 5G
> SECURITY_PATCH = 2023-06-01
> BASE_OS = 
> RELEASE = 12
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = motorola
> RELEASE_OR_CODENAME = 12
> SDK_INT = 31
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 31
> brand = motorola
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 5d8c81-392f6
> 
> 
> Error Message : java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
> 	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
> 	at com.rk.xededitor.App.onCreate$lambda$2(App.kt:45)
> 	at com.rk.xededitor.App.$r8$lambda$RirlTQxKpIxmHzKy_5qXCooNBmY(Unknown Source:0)
> 	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at com.rk.libcommons.After$1.invokeSuspend(After.kt:23)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3f52c2a, Dispatchers.Default]
> 

Clear app data to fix the issue
