### ISSUE TITLE
1 error

### ISSUE THREAD

**Issue by muhammadfadelalexander** [RohitKushvaha01/Xed-Editor#175]
I'm just curious, what error is that?
![Screenshot_20241005-084141_Karbon](https://github.com/user-attachments/assets/acca6dbd-7c13-485d-9cb5-bedccd90dcaf)

**Comment by RohitKushvaha01** [comment]
> I'm just curious, what error is that? ![Screenshot_20241005-084141_Karbon](https://private-user-images.githubusercontent.com/102850326/373835879-acca6dbd-7c13-485d-9cb5-bedccd90dcaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTM2MzEsIm5iZiI6MTcyODA5MzMzMSwicGF0aCI6Ii8xMDI4NTAzMjYvMzczODM1ODc5LWFjY2E2ZGJkLTdjMTMtNDg1ZC05Y2I1LWJlZGNjZDkwZGNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMTU1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzRmYWU3NmMxMjcyYzgzOGU3MGJkMTZkNzQ5ODc4NDQ5ZjdlMjU0Y2VlMTUzZTYwNTZlMTM1MzFkYjExMGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X7WKTDNi_XjQRmf2pQ5LXnacG-eF6zEpZTMjwpimwDw)

That is not an actual error. If you experience crashes or permission issues, try toggling the options in the terminal settings on or off.
