### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SweetRolls01** [RohitKushvaha01/Xed-Editor#177]
Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
Unix Time : 1728116264508
LocalTime : Oct 5, 2024 11:17:44 AM

ACTIVE_CODENAMES = []
app_version = 2.7.3
device_model = 220733SG
SECURITY_PATCH = 2024-09-01
BASE_OS = 
RELEASE = 12
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 12
SDK_INT = 31
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 31
brand = Redmi
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = V13.0.18.0.SGMEUXM

Error Message : java.lang.String cannot be cast to java.lang.Boolean
Error Cause : null
Error StackTrace : 

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
	at com.rk.xededitor.App.onCreate$lambda$2(App.kt:45)
	at com.rk.xededitor.App.$r8$lambda$RirlTQxKpIxmHzKy_5qXCooNBmY(Unknown Source:0)
	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at com.rk.libcommons.After$1.invokeSuspend(After.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c809543, Dispatchers.Default]

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'DefaultDispatcher-worker-1'
> Unix Time : 1728116264508
> LocalTime : Oct 5, 2024 11:17:44 AM
> 
> ACTIVE_CODENAMES = []
> app_version = 2.7.3
> device_model = 220733SG
> SECURITY_PATCH = 2024-09-01
> BASE_OS = 
> RELEASE = 12
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Xiaomi
> RELEASE_OR_CODENAME = 12
> SDK_INT = 31
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 31
> brand = Redmi
> supported_abi = [armeabi-v7a,armeabi]
> INCREMENTAL = V13.0.18.0.SGMEUXM
> 
> 
> Error Message : java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
> 	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:37)
> 	at com.rk.xededitor.App.onCreate$lambda$2(App.kt:45)
> 	at com.rk.xededitor.App.$r8$lambda$RirlTQxKpIxmHzKy_5qXCooNBmY(Unknown Source:0)
> 	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at com.rk.libcommons.After$1.invokeSuspend(After.kt:23)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c809543, Dispatchers.Default]
> 

Clear app data to fix the issue
