### ISSUE TITLE
QUERY_ALL_PACKAGES?

### ISSUE THREAD

**Issue by IzzySoft** [RohitKushvaha01/Xed-Editor#18]
The scanner here just reported on your latest APK:

    ! repo/com.rk.xededitor_20.apk declares sensitive permission(s): android.permission.QUERY_ALL_PACKAGES

Could you please clarify what this permission is needed for? The app description gave me no clue. Thanks in advance!

**Comment by RohitKushvaha01** [comment]
> The scanner here just reported on your latest APK:
> 
>     ! repo/com.rk.xededitor_20.apk declares sensitive permission(s): android.permission.QUERY_ALL_PACKAGES
> 
> Could you please clarify what this permission is needed for? The app description gave me no clue. Thanks in advance!

Thank you for reaching out. The android.permission.QUERY_ALL_PACKAGES permission is required for the upcoming plugin system. This system allows Xed-Editor to find specific apps (plugins) that has "xedpluginApi" in their manifest metadata,

**Comment by IzzySoft** [comment]
Thanks a lot! Added to your app's "green list" then:

![image](https://github.com/RohitKushvaha01/Xed-Editor/assets/6781438/bc9db839-8d6f-4dbe-a843-d82ca21d1da0)

Though it might/would be better to declare permissions only when they are really used :stuck_out_tongue_winking_eye:

**Comment by RohitKushvaha01** [comment]
> Oops – today two new ones turned up:
> 
> ```
> ! repo/com.rk.xededitor_27.apk declares sensitive permission(s): android.permission.MANAGE_EXTERNAL_STORAGE android.permission.READ_EXTERNAL_STORAGE
> ```
> 
> Looking at the changelog: related to the terminal?

Previously, I utilized the Storage Access Framework (SAF), which did not require explicit file permissions. However, its performance was significantly slow. Therefore, I decided to transition away from SAF and opted to read and write directly to the internal storage using the necessary file permissions.

**Comment by IzzySoft** [comment]
Yeah, performance can be a bottleneck there. Wasn't aware it would affect an editor that hard, though, where you usually do not process many files at once. OK, added that to the "green list" accordingly. Thanks!
