### ISSUE TITLE
Option to disable custom cursor

### ISSUE THREAD

**Issue by Markus40** [RohitKushvaha01/Xed-Editor#21]
**Is your feature request related to a problem? Please describe.**
I already have copy and paste on my keyboard and the custom text selection takes away the share option and all the other functions I normally have when selecting text. Personally, I don't like the delay and slowness of the smooth cursor movement.

**Describe the solution you'd like**
Have an option to return to normal cursor and text selection. If possible, have separate options for cursor smoothing, cursor appearance and the text selection menu.

**Comment by RohitKushvaha01** [comment]
> **Is your feature request related to a problem? Please describe.** I already have copy and paste on my keyboard and the custom text selection takes away the share option and all the other functions I normally have when selecting text. Personally, I don't like the delay and slowness of the smooth cursor movement.
> 
> **Describe the solution you'd like** Have an option to return to normal cursor and text selection. If possible, have separate options for cursor smoothing, cursor appearance and the text selection menu.

i have filed the issue in the upstream editor and it may take upto few months

**Comment by RohitKushvaha01** [comment]
due to how the editor is built, using system curser is not possible but i added share button in the text handler window + reduced delay
