### ISSUE TITLE
Option to ignore spaces when wrapping text

### ISSUE THREAD

**Issue by Markus40** [RohitKushvaha01/Xed-Editor#22]
**Is your feature request related to a problem? Please describe.**
When text wraps to a new line and the space does not fit on the previous line, it is moved to the beginning of the next line. This makes normal text a little harder to read.

**Describe the solution you'd like**
Have an option to ignore the space at the start of a new line when wrapping text.

**Comment by RohitKushvaha01** [comment]
> **Is your feature request related to a problem? Please describe.**
> When text wraps to a new line and the space does not fit on the previous line, it is moved to the beginning of the next line. This makes normal text a little harder to read.
> 
> **Describe the solution you'd like**
> Have an option to ignore the space at the start of a new line when wrapping text.

This feature requires modifying core editor framework and it does not worth the effort for such a small feature
