### ISSUE TITLE
Long text in option menu unreadable

### ISSUE THREAD

**Issue by Markus40** [RohitKushvaha01/Xed-Editor#24]
**Describe the bug**
In the settings menu, there is a longer option that is truncated and unreadable.

**Screenshots**
![Screenshot_20240630_145629_Xed Editor](https://github.com/RohitKushvaha01/Xed-Editor/assets/83376570/4a5901b5-ef78-4c17-a462-b33458d1de52)

 - Device: Samsung Galaxy A52 5G
 - OS: One UI 6.1
 - Android Version: Android 14

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> In the settings menu, there is a longer option that is truncated and unreadable.
> 
> **Screenshots**
> ![Screenshot_20240630_145629_Xed Editor](https://github.com/RohitKushvaha01/Xed-Editor/assets/83376570/4a5901b5-ef78-4c17-a462-b33458d1de52)
> 
>  - Device: Samsung Galaxy A52 5G
>  - OS: One UI 6.1
>  - Android Version: Android 14

It's "Anti Word breaking for word wrap"

When enabled with word wrap it moves the word to new line

**Comment by Markus40** [comment]
Would it be possible to expand the text to several lines with one click? This would keep the aesthetics and make it readable.
