### ISSUE TITLE
theme change doesn't  work

### ISSUE THREAD

**Issue by asmanel** [RohitKushvaha01/Xed-Editor#26]
On my phone, a old Samsung Galaxy A7,  when I change the theme in the setttings then restart the app, the theme remain the white one.

When I go back to the setting,s the theme settibg is how I left it.

Visibly, the other settings work properly but this one remain ignored.

**Comment by RohitKushvaha01** [comment]
> Why its closed, even though dark mode toggle not working

Can you send a screen recording of this issue?

**Comment by RohitKushvaha01** [comment]
> Here [Video](https://github.com/user-attachments/assets/cf4e0c61-8998-4165-a1f2-81faa66b10dc)

try this debug build 

https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/9954670715

**Comment by RohitKushvaha01** [comment]
> It still not working

if 2.2.1 not working for you i honestly have no idea why
clearing app data may work
