### ISSUE TITLE
Pure black/OLED theme (feature request)

### ISSUE THREAD

**Issue by badcodecat** [RohitKushvaha01/Xed-Editor#3]
I noticed you have support for dark and light themes, and I was wondering if you could add a pure black theme. Pure black themes save battery on OLED screens and since this is an android-first editor I thought you might be interested in the idea.

**Comment by RohitKushvaha01** [comment]
> I noticed you have support for dark and light themes, and I was wondering if you could add a pure black theme. Pure black themes save battery on OLED screens and since this is an android-first editor I thought you might be interested in the idea.

Thanks for your suggestion I will add it in next release
