### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Kadawe512** [RohitKushvaha01/Xed-Editor#39]
Fatal Crash occurred on Thread named 'Thread-12'
Unix Time : 1721623314000
LocalTime : 22‏/07‏/2024 7:41:54 ص

ACTIVE_CODENAMES = []
app_version = 2.2.1
device_model = 2201117SG
SECURITY_PATCH = 2024-06-01
BASE_OS = 
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = Xiaomi
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
brand = Redmi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V816.0.2.0.TKEMIXM

Error Message : Failed to allocate a 131854144 byte allocation with 25165824 free bytes and 29MB until OOM, target footprint 262809352, growth limit 268435456
Error Cause : null
Error StackTrace : 

java.lang.OutOfMemoryError: Failed to allocate a 131854144 byte allocation with 25165824 free bytes and 29MB until OOM, target footprint 262809352, growth limit 268435456
	at java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
	at java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:233)
	at java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1685)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:692)
	at java.lang.StringBuilder.append(StringBuilder.java:242)
	at io.github.rosemoe.sora.text.Content.toStringBuilder(Unknown Source:38)
	at io.github.rosemoe.sora.text.Content.toString(Unknown Source:0)
	at com.rk.xededitor.MainActivity.DynamicFragment$$ExternalSyntheticLambda1.run(Unknown Source:47)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-12'
> Unix Time : 1721623314000
> LocalTime : 22‏/07‏/2024 7:41:54 ص
> 
> ACTIVE_CODENAMES = []
> app_version = 2.2.1
> device_model = 2201117SG
> SECURITY_PATCH = 2024-06-01
> BASE_OS = 
> RELEASE = 13
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = Xiaomi
> RELEASE_OR_CODENAME = 13
> RELEASE_OR_PREVIEW_DISPLAY = 13
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 33
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 33
> brand = Redmi
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = V816.0.2.0.TKEMIXM
> 
> 
> Error Message : Failed to allocate a 131854144 byte allocation with 25165824 free bytes and 29MB until OOM, target footprint 262809352, growth limit 268435456
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.OutOfMemoryError: Failed to allocate a 131854144 byte allocation with 25165824 free bytes and 29MB until OOM, target footprint 262809352, growth limit 268435456
> 	at java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
> 	at java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:233)
> 	at java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1685)
> 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:692)
> 	at java.lang.StringBuilder.append(StringBuilder.java:242)
> 	at io.github.rosemoe.sora.text.Content.toStringBuilder(Unknown Source:38)
> 	at io.github.rosemoe.sora.text.Content.toString(Unknown Source:0)
> 	at com.rk.xededitor.MainActivity.DynamicFragment$$ExternalSyntheticLambda1.run(Unknown Source:47)
> 	at java.lang.Thread.run(Thread.java:1012)
> 

Your device doesn't have enough memory force stop or delete other apps to fix the issue
