### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Alexandru51** [RohitKushvaha01/Xed-Editor#4]
Why it is no longer an code editor?

**Comment by RohitKushvaha01** [comment]
> Why it is no longer an code editor?

Thank you for bringing this up. My focus initially is on building a solid foundation for the text editor functionality, ensuring it's robust and user-friendly. While syntax highlighting isn't currently supported (removed), i plan to incorporate language-specific features through plugins in the future. This approach allows for a more flexible and customizable experience for users.

**Comment by Alexandru51** [comment]
Oh, okay 👍🏻

**Comment by hasanelfalakiy** [comment]
> > Why it is no longer an code editor?
> 
> Thank you for bringing this up. My focus initially is on building a solid foundation for the text editor functionality, ensuring it's robust and user-friendly. While syntax highlighting isn't currently supported (removed), i plan to incorporate language-specific features through plugins in the future. This approach allows for a more flexible and customizable experience for users.

Will it allow for code suggestion, autocomplete, and running/compiling code with plugins?

**Comment by RohitKushvaha01** [comment]
> > > Why it is no longer an code editor?
> > 
> > Thank you for bringing this up. My focus initially is on building a solid foundation for the text editor functionality, ensuring it's robust and user-friendly. While syntax highlighting isn't currently supported (removed), i plan to incorporate language-specific features through plugins in the future. This approach allows for a more flexible and customizable experience for users.
> 
> Will it allow for code suggestion, autocomplete, and running/compiling code with plugins?

Yes,
You need to use [java reflection](https://www.oracle.com/technical-resources/articles/java/javareflection.html) to internal get methods and classes from xed

Here are some resources

- [Sora Editor api](https://project-sora.github.io/sora-editor-docs/guide/using-language) a editor library used in xed
- [Language Servers](https://github.com/fwcd/kotlin-language-server)

**Comment by hasanelfalakiy** [comment]
yes, but who will make a plugin for this (which I have explained)?

**Comment by RohitKushvaha01** [comment]
> yes, but who will make a plugin for this (which I have explained)?

You can create yourself or you have to wait few weeks

**Comment by hasanelfalakiy** [comment]
how to make it yourself? I'm still a beginner

**Comment by RohitKushvaha01** [comment]
> how to make it yourself? I'm still a beginner
- Download this plugin demo project
[xedPluginDemo.tar.gz](https://github.com/user-attachments/files/16104155/xedPluginDemo.tar.gz)

- Extract this tar.gz archive
- Open the project in Android studio
- Build it install on your device
- Open Xed Editor 
- Enable Plugin Toggle
- Restart
- Open again
- Enable the plugin
- Profit

The code in the entry point will executed by xed editor

**Comment by hasanelfalakiy** [comment]
okay thanks I'll try it
