### ISSUE TITLE
Make creating files more intuitive.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [RohitKushvaha01/Xed-Editor#45]
#### **Is your feature request related to a problem? **

I am solely able to create files outside the application, and then modify them utilizing it – there is no button to create one.

#### **Describe the solution you'd like**

Allow them to be created using the application.

**Comment by RohitKushvaha01** [comment]
> #### **Is your feature request related to a problem? **
> I am solely able to create files outside the application, and then modify them utilizing it – there is no button to create one.
> 
> #### **Describe the solution you'd like**
> Allow them to be created using the application.
> 
> #### **Describe alternatives you've considered**
> #### **Additional context**

you can create file and folder by long pressing a folder

**Comment by RokeJulianLockhart** [comment]
> https://github.com/RohitKushvaha01/Xed-Editor/issues/45#issuecomment-2247567860

@RohitKushvaha01, that's utterly unintuitive. You'll have a lot of users abandon this if they can't easily ascertain how to perform basic actions.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/RohitKushvaha01/Xed-Editor/issues/45#issuecomment-2247737656

@RohitKushvaha01, merely a button labelled "Create file" beside the "Open file" one.

There's also the general rule that long-press for anything (even selection) should generally be avoided for accessibility and intuitivity reasons, so maybe the other actions that require long-presses should be reconsidered, although that's the purview of another issue of broader scope.
