### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by pidjan** [RohitKushvaha01/Xed-Editor#46]
List of features i'd like to see in Xed Editor:
1. Improved file browser - icons based on files extension.
2. More customization - themes, fonts(from android itself, with changing size, ligatures), zoom level, cursor type.
3. Tab button - with changing tab size, insert spaces. (or don't add tab button in ui, but let users with keyboard connected to phone/tab on keyboard like in hacker's keyboard have this feature)
4. Code highlighting, support language servers (like in neovim/zed), etc.
5. convert assets to bytes and use them where do you want for (maybe) faster speed.

**Comment by pidjan** [comment]
@RohitKushvaha01 , "Tab" button should work like in Visual Studio Code, when you press it, it either insert multiple spaces (how many - user should specify in settings, by default - 4 spaces) or just insert ascii tab character. I want it to be either in interface while you change file, or user should have it physically on keyboard (for example, in hacker's keyboard from f-droid)

**Comment by RohitKushvaha01** [comment]
> Can you add a save button shortcut for better navigation.
> 
> ![save](https://github.com/user-attachments/assets/75193c9f-584f-450e-882e-13ec69614ca5)

Did you mean CTRL+S?

**Comment by RohitKushvaha01** [comment]
> I mean that icon not CTRL+S

Could you explain "add a save button shortcut for better navigation" in more details?

**Comment by RohitKushvaha01** [comment]
> It just a save button like undo redo shortcut, when you edit code you have to go and click three dots then save for any changes, what it does is you can access it outside like undo and redo icon.

You can already do that 

https://github.com/user-attachments/assets/43fd6840-d83e-424a-80de-e9a8a476aa7f

**Comment by urmomseksy** [comment]
> @RohitKushvaha01 , "Tab" button should work like in Visual Studio Code, when you press it, it either insert multiple spaces (how many - **user should specify in settings, by default - 4 spaces)** or just insert ascii tab character. I want it to be either in interface while you change file, or user should have it physically on keyboard (for example, in hacker's keyboard from f-droid)

Is there supposed to be a setting in version 2.5.0 to adjust the spaces? 

I noticed the spacing is way different between other text editors and it would be nice to be able to adjust this. But I'm just not seeing the option.
