### ISSUE TITLE
don't close all folders after deleting

### ISSUE THREAD

**Issue by pidjan** [RohitKushvaha01/Xed-Editor#49]
**Describe the bug**
don't close all folders after deleting something/other actions

**To Reproduce**
1. Open as many folders and subfolders you want.
2. Delete random folder/file you don't need.
3. All folders are folded, and you should open them again:(

**Expected behavior**
Folder should be just deleted, without folding all folders

**Screenshots**

**complete the following information):**
 - Device: Galaxy S21 
 - OS: One UI 6.1
 - Android Version A14

**logcat output/logcat.txt(if applicable)**

**Additional context**

**Comment by RohitKushvaha01** [comment]
> **Describe the bug** don't close all folders after deleting something/other actions
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open as many folders and subfolders you want.
> 2. Delete random folder/file you don't need.
> 3. All folders are folded, and you should open them again:(
> 
> **Expected behavior** Folder should be just deleted, without folding all folders
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **complete the following information):**
> 
> * Device: Galaxy S21
> * OS: One UI 6.1
> * Android Version A14
> 
> **logcat output/logcat.txt(if applicable)**
> 
> **Additional context** Add any other context about the problem here.

fixed https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10131407135#artifacts
