### ISSUE TITLE
Batch Replacement of Text

### ISSUE THREAD

**Issue by Pantyhose-X** [RohitKushvaha01/Xed-Editor#5]
The Batch >> button in the Replace dialog extends the dialog box to include a list for multiple Find/Replace combinations with options. Pressing the Batch Replace All button then replaces all of the multiple matched strings with the respective specified strings. This user interface allows much faster and more intuitive replace operations for frequent use of the replace feature.

**Comment by RohitKushvaha01** [comment]
> 

Can you explain the issue?

**Comment by RohitKushvaha01** [comment]
Fixed in latest commit release not published yet
