### ISSUE TITLE
Design issue 

### ISSUE THREAD

**Issue by Raffa064** [RohitKushvaha01/Xed-Editor#50]
**Describe the bug**
The Enable/Disable plugin toggler and the plugin manager aren't at the same interface in the app's settings. This isn't a very intuitive layout at first.

![Screenshot_2024-07-25-06-21-52-029_com rk xededitor](https://github.com/user-attachments/assets/4c19fe3e-c3df-4182-9c4f-1c554f2d0368)
![Screenshot_2024-07-25-06-21-45-708_com rk xededitor](https://github.com/user-attachments/assets/d8947ed5-3c09-46e0-ba5f-dd0451781073)
![Screenshot_2024-07-25-06-21-49-470_com rk xededitor](https://github.com/user-attachments/assets/44f733dd-d9a2-46c2-a0cc-329e84769563)

**Comment by RohitKushvaha01** [comment]
Fixed
