### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Raffa064** [RohitKushvaha01/Xed-Editor#55]
Fatal Crash occurred on Thread named 'Thread-27'
Unix Time : 1722137538235
LocalTime : Jul 28, 2024 00:32:18

ACTIVE_CODENAMES = []
app_version = 2.5.0
device_model = POCOPHONE F1
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2020-12-01
BASE_OS = 
RELEASE = 10
CODENAME = REL
manufacturer = Xiaomi
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 27
PREVIEW_SDK_INT = 0
SDK = 29
brand = Xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V12.0.3.0.QEJMIXM

Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:97)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:919)

**Comment by Raffa064** [comment]
The crash report above occurred when I tryied to open a directory.

There's another problem (version 2.5):

When I open individual files it doesn't show their content in editor.

**Comment by RohitKushvaha01** [comment]
> The crash report above occurred when I tryied to open a directory.
> 
> There's another problem (version 2.5):
> 
> When I open individual files it doesn't show their content in editor.

are you trying to acces Android/data files ?

**Comment by Raffa064** [comment]
> > The crash report above occurred when I tryied to open a directory.
> > There's another problem (version 2.5):
> > When I open individual files it doesn't show their content in editor.
> 
> are you trying to acces Android/data files ?

No, the dir is at

/storage/emulated/0/AppProjects/ModifyCore

**Comment by RohitKushvaha01** [comment]
> > > The crash report above occurred when I tryied to open a directory.
> > > There's another problem (version 2.5):
> > > When I open individual files it doesn't show their content in editor.
> > 
> > 
> > are you trying to acces Android/data files ?
> 
> No, the dir is at
> 
> /storage/emulated/0/AppProjects/ModifyCore

try  this if it work

https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10137803325#artifacts

**Comment by Raffa064** [comment]
> > > > The crash report above occurred when I tryied to open a directory.
> > > > There's another problem (version 2.5):
> > > > When I open individual files it doesn't show their content in editor.
> > > 
> > > 
> > > are you trying to acces Android/data files ?
> > 
> > 
> > No, the dir is at
> > /storage/emulated/0/AppProjects/ModifyCore
> 
> try this if it work
> 
> https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10137803325#artifacts

Also gives the same error:

Fatal Crash occurred on Thread named 'Thread-7'
Unix Time : 1722251742686
LocalTime : Jul 29, 2024 08:15:42

ACTIVE_CODENAMES = []
app_version = 2.5.0
device_model = POCOPHONE F1
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2020-12-01
BASE_OS = 
RELEASE = 10
CODENAME = REL
manufacturer = Xiaomi
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 27
PREVIEW_SDK_INT = 0
SDK = 29
brand = Xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V12.0.3.0.QEJMIXM


Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:190)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:34)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:919)

**Comment by Raffa064** [comment]
The error is permission related, as I was able to open the folder "/data/data/com.ek.xededitor"

![Screenshot_2024-07-29-08-19-32-495_com rk xededitor](https://github.com/user-attachments/assets/f77e31c4-d27d-43eb-be41-8469e170dc90)

Any other folder in the Android root (/storage/emulated/0) continues to give that error, which did not exist before release 2.5

**Comment by RohitKushvaha01** [comment]
> The error is permission related, as I was able to open the folder "/data/data/com.ek.xededitor"
> 
> ![Screenshot_2024-07-29-08-19-32-495_com rk xededitor](https://github.com/user-attachments/assets/f77e31c4-d27d-43eb-be41-8469e170dc90)
> 
> Any other folder in the Android root (/storage/emulated/0) continues to give that error, which did not exist before release 2.5

Well, you have to grant manage storage permission 

https://github.com/user-attachments/assets/0bd900bc-c679-4c80-8878-756acdfa3faf

**Comment by Raffa064** [comment]
I've already granted the permission 

Video: https://www.mediafire.com/file/v39cjw26n5rz0ax/Karbon/file

**Comment by Raffa064** [comment]
It works now!
