### ISSUE TITLE
Terminal Key support

### ISSUE THREAD

**Issue by soli-rsa** [RohitKushvaha01/Xed-Editor#56]
**Describe the bug**
Terminal return key triggers escape extra-key on hardware keyboard

**To Reproduce**
1. Go to 'terminal'
2. Click on 'return key (unexpected keyboard2) '
3. Scroll down to ''

**Expected behavior**

**Screenshots**

**complete the following information):**
 
Device
Board: 	NEN
Codename: 	REL
Device Name: 	HUAWEI NEN-LX1
Hardware: 	qcom
ID: 	HUAWEINEN-LX1
Manufacture: 	HUAWEI
Model: 	NEN-LX1
Product: 	NEN-L01CQ

System
API Level: 	29
Android: 	10
Kernel: 	4.19.95+
Preview SDK: 	0
Security Patch Level: 	2020-07-01
VM Version: 	ART 2.1.0

CPU
ABI: 	arm64-v8a
CPU Freq: 	4 x 2016MHz - 300MHz 4 x 1804MHz - 300MHz
CPU cores: 	8

Memory
Low Ram device: 	false
Ram: 	5700 MB

Display
Ratio: 	11:5
Resolution: 	1080 x 2376
xdpi / ydpi: 	398 / 392 dpi

Features
Bluetooth: 	true
GPS: 	true
NFC: 	true

Software
WebView Implementation: 	Huawei WebView 12.1.2.323

**Comment by RohitKushvaha01** [comment]
fixed https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10137404987#artifacts
