### ISSUE TITLE
App name suggestion

### ISSUE THREAD

**Issue by rabaimorp** [RohitKushvaha01/Xed-Editor#57]
I was really confused when I saw "Karbon" on my home page after obtanium auto updated xed editor in the background. In my opinion Karbon sounds way too generic. My name ideas:
Xedroid
Androditor

**Comment by RohitKushvaha01** [comment]
> I was really confused when I saw "Karbon" on my home page after obtanium auto updated xed editor in the background. In my opinion Karbon sounds way too generic. My name ideas:
> Xedroid
> Androditor
> 

Thanks for sharing your thoughts! I get how the name change to "Karbon" might have been surprising. I picked "Karbon" because it's simple and catchy, and i think it fits the app well. Your suggestions are cool, but i am sticking with "Karbon" for now. Appreciate your understanding and thanks for the input!

**Comment by rabaimorp** [comment]
My issue isn't that "Karbon" is not catchy, I just liked that about the previous name that you had a guess that what the program was about the name. I think something like "KarbonEdit" would be nice, and more memorable as well.

**Comment by RohitKushvaha01** [comment]
> My issue isn't that "Karbon" is not catchy, I just liked that about the previous name that you had a guess that what the program was. I think something like "KarbonEdit" would be nice, and more memorable as well.

I think you're correct 😃 I will change the name to something similar to "KarbonEdit"

**Comment by rabaimorp** [comment]
Awesome, I get that my first two names were kinda extra. Are you planning to keep the package name as "com.rk.xededitor" ? I understand that changing it could be really difficult.

**Comment by RohitKushvaha01** [comment]
> Awesome, I get that my first two names were kinda extra. Are you planning to keep the package name as "com.rk.xededitor" ? I understand that changing it could be really difficult.

Changing package name is very difficult because everyone using the app have to delete the previous version and reinstall new one
and that's not a good idea

**Comment by urmomseksy** [comment]
You could put a personal flair on the name.

'RohEdit' or 'KushvEditor' 

Both names would sound kind of cool in English. 

I don't really care what the name is since the app is awesome no matter what, I just was bored and felt like chiming in in case you were open to any other suggestions.

**Comment by rabaimorp** [comment]
😶
