### ISSUE TITLE
Indent/outdent toolbar buttons for easier indentation handling with phone keyboards

### ISSUE THREAD

**Issue by 5310** [RohitKushvaha01/Xed-Editor#66]
**Is your feature request related to a problem? Please describe.**

Android on-screen keyboards don't usually have tab keys: None of the Gboard layouts do, for example, not even the "PC" layouts. 

I often find myself needing to indent my lines, especially when editing code. And while I can use spaces to indent, I can't use backspace to outdent my lines in Xed Android—backspaces stop removing characters if the app detects that only spaces remain to the start of a line. 

This in itself is very handy for drafting lists and outlines, but leaves me unable to outdent my lines without considerable effort having to manually select the spaces I want removed and then deleting them. 

**Describe the solution you'd like**

Please consider adding a pair of indent and outdent buttons to the toolbar. 

- When the indent button is pressed, a tab character is prepended to the current line (or currently selected lines)
- When the outdent button is pressed, a tab is removed from the start of the current line (or currently selected lines), if possible

**Additional context**

These buttons would fit well with any indentation preferences added in the future in terms of whether the user wants tabs to ident their files, or a certain number of spaces, etc. Tab being the initial sensible default :]

**Comment by RohitKushvaha01** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Android on-screen keyboards don't usually have tab keys: None of the Gboard layouts do, for example, not even the "PC" layouts.
> 
> I often find myself needing to indent my lines, especially when editing code. And while I can use spaces to indent, I can't use backspace to outdent my lines in Xed Android—backspaces stop removing characters if the app detects that only spaces remain to the start of a line.
> 
> This in itself is very handy for drafting lists and outlines, but leaves me unable to outdent my lines without considerable effort having to manually select the spaces I want removed and then deleting them.
> 
> **Describe the solution you'd like**
> 
> Please consider adding a pair of indent and outdent buttons to the toolbar.
> 
>     * When the indent button is pressed, a tab character is prepended to the current line (or currently selected lines)
> 
>     * When the outdent button is pressed, a tab is removed from the start of the current line (or currently selected lines), if possible
> 
> 
> **Additional context**
> 
> These buttons would fit well with any indentation preferences added in the future in terms of whether the user wants tabs to ident their files, or a certain number of spaces, etc. Tab being the initial sensible default :]

https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10195033457

**Comment by 5310** [comment]
Thank you for the very prompt implementation! 

I didn't realize an extra-keys bar was already in the works :sweat_smile: The up and down keys are also much appreciated. Together with Tab and Home, we can achieve the same line-wide indentation for single lines, and Tab by itself is more flexible!

It does seem the [GH-actions build](https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10195033457) has an issue with word-wrap: 
-	With Word-wrap enabled: Tab adds a tab character but also causes the current line to wrap, even if it's a completely empty line
	- Is this being cased by the [ZWNJ space](https://github.com/RohitKushvaha01/Xed-Editor/commit/3e43349cfb0a3b8529368885002e97e6a120d78c#diff-b2ef4e679a7ef2ec0f2efeb0babbe4a1dd2e60f14358ccd79ae16ededb76bb19R330)? :confused: 
- This places the cursor at the start of seems like a new line, but is only the current empty line wrapped over
	- Starting to type does snap the cursor back after the tab in the original line, collapsing it to a normal unwrapped form

Also: Hitting enter / creating a newline after a tabbed line maintains the indentation using spaces rather than tabs now!
- This in turns breaks the Untab key as it only works on tabs right before the cursor

**Comment by 5310** [comment]
While totally unrelated to the topic of this Issue, I feel compelled to at least note down some other issues I noticed in this build immediately—
1. Entirety of `/storage/emulated/0/Downloads/` is now blocklisted, but it isn't clearly explained
	- Trying to open any individual files within Downloads fails
		- Even files created in and edited with the app just last night!
		- Now it just opens a randomly numbered empty file!
			- There is no explanation given
	- Only once I tried to open Downloads as a folder did I got the explanatory popup
		- This explanation should also be given when trying to open an individual file
2. There is no way to create new files without first opening a folder
	- This used to be how I used the app until yesterday as well, so I was extra confused :sweat_smile: 
	- Even after opening a folder, the option to create a file is nested within the overflow menu of the sidebar
		- Which is not very discoverable for something that used to a button on the sidebar itself!
