### ISSUE TITLE
renaming the file causes crash

### ISSUE THREAD

**Issue by pidjan** [RohitKushvaha01/Xed-Editor#67]
**Describe the bug**
renaming the file causes crash, while the name of the file actually changes. (also check additional context)
```
Fatal Crash occurred on Thread named 'main'
Unix Time : 1722520553249
LocalTime : 1 авг. 2024 г. 16:55:53

ACTIVE_CODENAMES = []
app_version = 2.5.0
device_model = SM-G991B
SEM_INT = 3401
SECURITY_PATCH = 2024-05-01
BASE_OS = samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXUAGXDA:user/release-keys
SEM_FIRST_SDK_INT = 30
RELEASE = 14
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 14
RELEASE_OR_PREVIEW_DISPLAY = 14
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 34
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 34
SEM_PLATFORM_INT = 150100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = G991BXXSBGXDH


Error Message : null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter.renameFile(TreeViewAdapter.kt:136)
	at com.rk.xededitor.MainActivity.treeview2.FileAction.rename$lambda$7(FileAction.kt:395)
	at com.rk.xededitor.MainActivity.treeview2.FileAction.$r8$lambda$qWFghtCvaQbHtHGYiFUDtMA9U5I(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.FileAction$$ExternalSyntheticLambda3.onClick(D8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
**To Reproduce**
1. hold file
2. click rename
3. change the name
4. press the button to change
5. causes fatal error and infinite "please wait" screen

**Expected behavior**
N/A

**Screenshots**

**complete the following information):**
 - Device: Galaxy S21
 - OS: One UI 6.1
 - Android Version: A14

**logcat output/logcat.txt(if applicable)**
N/A

**Additional context**
also, please, add "tab size" slider (1-4) in settings

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> renaming the file causes crash, while the name of the file actually changes. (also check additional context)
> ```
> Fatal Crash occurred on Thread named 'main'
> Unix Time : 1722520553249
> LocalTime : 1 авг. 2024 г. 16:55:53
> 
> ACTIVE_CODENAMES = []
> app_version = 2.5.0
> device_model = SM-G991B
> SEM_INT = 3401
> SECURITY_PATCH = 2024-05-01
> BASE_OS = samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXUAGXDA:user/release-keys
> SEM_FIRST_SDK_INT = 30
> RELEASE = 14
> MEDIA_PERFORMANCE_CLASS = 0
> CODENAME = REL
> manufacturer = samsung
> RELEASE_OR_CODENAME = 14
> RELEASE_OR_PREVIEW_DISPLAY = 14
> KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
> SDK_INT = 34
> PREVIEW_SDK_FINGERPRINT = REL
> PREVIEW_SDK_INT = 0
> SDK = 34
> SEM_PLATFORM_INT = 150100
> brand = samsung
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = G991BXXSBGXDH
> 
> 
> Error Message : null
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException
> 	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter.renameFile(TreeViewAdapter.kt:136)
> 	at com.rk.xededitor.MainActivity.treeview2.FileAction.rename$lambda$7(FileAction.kt:395)
> 	at com.rk.xededitor.MainActivity.treeview2.FileAction.$r8$lambda$qWFghtCvaQbHtHGYiFUDtMA9U5I(Unknown Source:0)
> 	at com.rk.xededitor.MainActivity.treeview2.FileAction$$ExternalSyntheticLambda3.onClick(D8$$SyntheticClass:0)
> 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:230)
> 	at android.os.Looper.loop(Looper.java:319)
> 	at android.app.ActivityThread.main(ActivityThread.java:8919)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
> ```
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. hold file
> 2. click rename
> 3. change the name
> 4. press the button to change
> 5. causes fatal error and infinite "please wait" screen
> 
> **Expected behavior**
> N/A
> 
> **Screenshots**
> 
> 
> **complete the following information):**
>  - Device: Galaxy S21
>  - OS: One UI 6.1
>  - Android Version: A14
> 
> **logcat output/logcat.txt(if applicable)**
> N/A
> 
> **Additional context**
> also, please, add "tab size" slider (1-4) in settings and fix the bug with extra keys displaying:
> ![Screenshot_20240801_170420_Karbon](https://github.com/user-attachments/assets/33f8c901-2f87-4f60-8863-4a5254702891)
> 

Custom tabs are done just this rename error needs to be fixed
