### ISSUE TITLE
Status bar incorrect color

### ISSUE THREAD

**Issue by AndroMaster436** [RohitKushvaha01/Xed-Editor#68]
**Describe the bug**
For some reason, the color of the status bar now does not match the color of the application design

**To Reproduce**
Just open app

**Expected behavior**
The colors of the status bar and application should be combined

**Screenshots**
With AMOLED theme - no problem
![Screenshot_20240802-143622~2](https://github.com/user-attachments/assets/8b997e31-0691-40b6-9ab9-fb6d0253cc60)
![Screenshot_20240802-143637~2](https://github.com/user-attachments/assets/05b0896c-e703-4575-8016-efca54747576)
![Screenshot_20240802-143649~2](https://github.com/user-attachments/assets/cef7ddc3-4c03-4a14-80fd-dcb870926cb3)

**complete the following information):**
 - Device: Redmi 10 (2021)
 - OS: Pixel Experience 11
 - Android 11

**Comment by AndroMaster436** [comment]
I have now found a new bug. Theme which: dark, light, auto - are not saved. After restarting the application, it is reset to auto -_-

**Comment by AndroMaster436** [comment]
Oops, I haven't noticed a new commit
Installing...

**Comment by RohitKushvaha01** [comment]
> I have now found a new bug. Theme which: dark, light, auto - are not saved. After restarting the application, it is reset to auto -_-

It's work is in progress

**Comment by AndroMaster436** [comment]
Why themes and extra keys are dropped???

**Comment by RohitKushvaha01** [comment]
> Why themes and extra keys are dropped???

What do you mean by "dropped" ?
They are still there

**Comment by AndroMaster436** [comment]
> > Why themes and extra keys are dropped???
> 
> What do you mean by "dropped" ? They are still there

![Screenshot_20240802-154818](https://github.com/user-attachments/assets/c403a237-b319-44a4-8aec-691f8504fd63)
This is from last commit

**Comment by AndroMaster436** [comment]
> > > Why themes and extra keys are dropped???
> > 
> > 
> > What do you mean by "dropped" ? They are still there
> 
> ![Screenshot_20240802-154818](https://private-user-images.githubusercontent.com/87223939/354598994-c403a237-b319-44a4-8aec-691f8504fd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDMyNzQsIm5iZiI6MTcyMjYwMjk3NCwicGF0aCI6Ii84NzIyMzkzOS8zNTQ1OTg5OTQtYzQwM2EyMzctYjMxOS00NGE0LThhZWMtNjkxZjg1MDRmZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEyNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YTFjYTkyNjBmMTBiZTcwNzkyNjNmZjZhZDY0OGFlNTY3MDk2OGI2YWY5Y2U3Mzk2MTU5OWQ5MDJiMGIyZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QR2wE34ouY_WKiLIcfvxwA-_txEIC0lhlutjdvlacZU) This is from last commit

It's in main branch. I just noticed

**Comment by RohitKushvaha01** [comment]
> > > Why themes and extra keys are dropped???
> > 
> > What do you mean by "dropped" ? They are still there
> 
> ![Screenshot_20240802-154818](https://github.com/user-attachments/assets/c403a237-b319-44a4-8aec-691f8504fd63)
> This is from last commit

Oh I accidentally modified main branch the themes and new stuff is on dev branch

**Comment by AndroMaster436** [comment]
> > > > Why themes and extra keys are dropped???
> > > 
> > > 
> > > What do you mean by "dropped" ? They are still there
> > 
> > 
> > ![Screenshot_20240802-154818](https://private-user-images.githubusercontent.com/87223939/354598994-c403a237-b319-44a4-8aec-691f8504fd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDMzMzcsIm5iZiI6MTcyMjYwMzAzNywicGF0aCI6Ii84NzIyMzkzOS8zNTQ1OTg5OTQtYzQwM2EyMzctYjMxOS00NGE0LThhZWMtNjkxZjg1MDRmZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEyNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjEzMGY5ODEzOGZiNWZkZTA1YWUxMjFlODBjNGVmMzVkZTg0NGM2MDJkYWUxYTk0NjcwN2FkY2Q5ZWJjYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JE4-dh7kiAnafovJmFAVs_s88_pdPPh3AUmjrm27orY)
> > This is from last commit
> 
> Oh I accidentally modified main branch the themes and new stuff is on dev branch

Nothing. Anything can happen 😁

**Comment by AndroMaster436** [comment]
If I had the skills to develop Android applications, I would help you

**Comment by RohitKushvaha01** [comment]
> If I had the skills to develop Android applications, I would help you


I appreciate your willingness to help! If you ever decide to learn or if you have other skills you think could be useful, I'd love to collaborate.
