### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MedievalSteel** [RohitKushvaha01/Xed-Editor#75]
Fatal Crash occurred on Thread named 'Thread-42'
Unix Time : 1722978917756
LocalTime : 2024年8月7日 05:15:17

ACTIVE_CODENAMES = []
app_version = 2.5.0
device_model = JSN-AL00a
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2020-08-01
BASE_OS = HONOR/JSN-AL00/HWJSN-H:10/HONORJSN-AL00/10.0.0.165C00:user/release-keys
RELEASE = 10
CODENAME = REL
manufacturer = HUAWEI
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 27
PREVIEW_SDK_INT = 0
SDK = 29
brand = HONOR
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = 10.0.0.168C00

Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:97)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:929)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-42'
> Unix Time : 1722978917756
> LocalTime : 2024年8月7日 05:15:17
> 
> ACTIVE_CODENAMES = []
> app_version = 2.5.0
> device_model = JSN-AL00a
> RESOURCES_SDK_INT = 29
> SECURITY_PATCH = 2020-08-01
> BASE_OS = HONOR/JSN-AL00/HWJSN-H:10/HONORJSN-AL00/10.0.0.165C00:user/release-keys
> RELEASE = 10
> CODENAME = REL
> manufacturer = HUAWEI
> SDK_INT = 29
> PREVIEW_SDK_FINGERPRINT = REL
> FIRST_SDK_INT = 27
> PREVIEW_SDK_INT = 0
> SDK = 29
> brand = HONOR
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = 10.0.0.168C00
> 
> 
> Error Message : listFiles(...) must not be null
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.NullPointerException: listFiles(...) must not be null
> 	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:97)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
> 	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at java.lang.Thread.run(Thread.java:929)
> 

Please use latest actions build for new features and bug fixes

https://github.com/RohitKushvaha01/Xed-Editor/actions/runs/10265992192#artifacts
