### ISSUE TITLE
gboard gestures in brackets

### ISSUE THREAD

**Issue by hasanelfalakiy** [RohitKushvaha01/Xed-Editor#78]
**Describe the bug**
There was a slight problem when after typing the first bracket I wanted to move the cursor to the right but couldn't, but if I moved to the left it worked normally.for curly brackets it is also normal to pass through the right and left sides, but when the brackets are inside a curly bracket block, the cursor can pass through the right and left brackets

**To Reproduce**
to reproduce it like a video I tap the editor anywhere then go back between the brackets then I slide with the space bar then it can go through normally

**Expected behavior**
can skip the right side brackets normally when shifting the cursor with space

**complete the following information):**
 - Device: [e.g. Vivo Y15 2019]
 - OS: [e.g. Funtouch OS 9]
 - Android Version [e.g. Android 11]
https://github.com/user-attachments/assets/d1f4d11b-9048-4422-9949-26eed4dca83b

**Comment by RohitKushvaha01** [comment]
> **Describe the bug** There was a slight problem when after typing the first bracket I wanted to move the cursor to the right but couldn't, but if I moved to the left it worked normally.for curly brackets it is also normal to pass through the right and left sides, but when the brackets are inside a curly bracket block, the cursor can pass through the right and left brackets
> 
> **To Reproduce** Steps to reproduce the behavior: to reproduce it like a video I tap the editor anywhere then go back between the brackets then I slide with the space bar then it can go through normally
> 
> **Expected behavior** can skip the right side brackets normally when shifting the cursor with space
> 
> **complete the following information):**
> 
> * Device: [e.g. Vivo Y15 2019]
> * OS: [e.g. Funtouch OS 9]
> * Android Version [e.g. Android 11]
>   https://github.com/user-attachments/assets/d1f4d11b-9048-4422-9949-26eed4dca83b

This seems to be an upstream issue with sora-editor and is likely tied to how the editor handles certain input events within bracketed blocks. this is not a very serious issue
