### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [RohitKushvaha01/Xed-Editor#8]
ref: https://monitor.f-droid.org/builds/log/com.rk.xededitor/12#site-footer

diff log:
```
│ │ │ │ │ │ │   --- xed-editor-v1.1.2/smali/com/rk/xededitor/activities/MainActivity/MainActivity.smali
│ │ │ │ │ │ ├── +++ com.rk.xededitor_12/smali/com/rk/xededitor/activities/MainActivity/MainActivity.smali
│ │ │ │ │ │ │ @@ -766,22 +766,14 @@
│ │ │ │ │ │ │      const/4 v1, 0x0
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      invoke-static {p0, p1, v0, v1}, Landroidx/core/app/b;->i(Landroid/app/Activity;Landroid/content/Intent;ILandroid/os/Bundle;)V
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      return-void
│ │ │ │ │ │ │  .end method
│ │ │ │ │ │ │  
│ │ │ │ │ │ │ -.method public redo(Landroid/view/View;)V
│ │ │ │ │ │ │ -    .locals 0
│ │ │ │ │ │ │ -
│ │ │ │ │ │ │ -    invoke-static {p0}, Lv1/g;->h(Landroid/content/Context;)V
│ │ │ │ │ │ │ -
│ │ │ │ │ │ │ -    return-void
│ │ │ │ │ │ │ -.end method
│ │ │ │ │ │ │ -
│ │ │ │ │ │ │  .method public reselect(Landroid/view/View;)V
│ │ │ │ │ │ │      .locals 3
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      new-instance v0, Ljava/util/ArrayList;
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V
│ │ │ │ │ │ │  
│ │ │ │ │ │ │ @@ -835,15 +827,7 @@
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      invoke-static {v0, v1}, Lv1/g;->i(Landroid/view/View;Z)V
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      invoke-virtual {p0, p1}, Lcom/rk/xededitor/activities/MainActivity/MainActivity;->open_folder(Landroid/view/View;)V
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      return-void
│ │ │ │ │ │ │  .end method
│ │ │ │ │ │ │ -
│ │ │ │ │ │ │ -.method public undo(Landroid/view/View;)V
│ │ │ │ │ │ │ -    .locals 0
│ │ │ │ │ │ │ -
│ │ │ │ │ │ │ -    invoke-static {p0}, Lv1/g;->h(Landroid/content/Context;)V
│ │ │ │ │ │ │ -
│ │ │ │ │ │ │ -    return-void
│ │ │ │ │ │ │ -.end method
```

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/eaadbf63a41fa9d07e61a8c8a6a7c829d8199dff

**Comment by licaon-kter** [comment]
no APKs published? https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v1.1.3

**Comment by RohitKushvaha01** [comment]
> no APKs published? https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v1.1.3

I wanted to delete that release please skip that version

**Comment by licaon-kter** [comment]
you tagged https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.0.1 from https://github.com/RohitKushvaha01/Xed-Editor/commit/31151e47273a9f2011fde6a0488e63324b7802ce

but the APK was built from ca80ccfade5184c8836ed2e9b21b0410336ecaad

:( https://gitlab.com/fdroid/fdroiddata/-/jobs/7190201007#L3179

**Comment by RohitKushvaha01** [comment]
> you tagged https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.0.1 from [31151e4](https://github.com/RohitKushvaha01/Xed-Editor/commit/31151e47273a9f2011fde6a0488e63324b7802ce)
> 
> but the APK was built from [ca80ccf](https://github.com/RohitKushvaha01/Xed-Editor/commit/ca80ccfade5184c8836ed2e9b21b0410336ecaad)
> 
> :( https://gitlab.com/fdroid/fdroiddata/-/jobs/7190201007#L3179
> 
> /LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/54aa1c8c920605d7b14e2c762fdb0ebbb5d2f8c8

what should i do now?

**Comment by licaon-kter** [comment]
build the APK from https://github.com/RohitKushvaha01/Xed-Editor/commit/31151e47273a9f2011fde6a0488e63324b7802ce and replace it in https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.0.1


/PS: there's the possibility that you built your APK from the UN-commited tree, so in the future, please, always build AFTER tagging :wink:

**Comment by RohitKushvaha01** [comment]
> build the APK from [31151e4](https://github.com/RohitKushvaha01/Xed-Editor/commit/31151e47273a9f2011fde6a0488e63324b7802ce) and replace it in https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.0.1
> 
> /PS: there's the possibility that you built your APK from the UN-commited tree, so in the future, please, always build AFTER tagging 😉

what if i create a new release?

**Comment by RohitKushvaha01** [comment]
> build the APK from [31151e4](https://github.com/RohitKushvaha01/Xed-Editor/commit/31151e47273a9f2011fde6a0488e63324b7802ce) and replace it in https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.0.1
> 
> /PS: there's the possibility that you built your APK from the UN-commited tree, so in the future, please, always build AFTER tagging 😉

i replaced the apk

**Comment by licaon-kter** [comment]
great :tada: https://gitlab.com/fdroid/fdroiddata/-/commit/8eb5a090425664b493985a1f63d91558441db10f

**Comment by licaon-kter** [comment]
Please upload the release APK built from the tagged commit, not from your working local tree: https://gitlab.com/fdroid/fdroiddata/-/jobs/7271972448#L1577

So build now from 92e52d71d371cfca346b9a759579663922f03a87 and update the APK in https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.1.0

**Comment by RohitKushvaha01** [comment]
> Please upload the release APK built from the tagged commit, not from your working local tree: https://gitlab.com/fdroid/fdroiddata/-/jobs/7271972448#L1577
> 
> So build now from [92e52d7](https://github.com/RohitKushvaha01/Xed-Editor/commit/92e52d71d371cfca346b9a759579663922f03a87) and update the APK in https://github.com/RohitKushvaha01/Xed-Editor/releases/tag/v2.1.0

I apologize for the confusion. It appears the issue was due to a misconfigured Android Studio environment, which led to building from the cache instead of the actual source. I've now correctly built the APK from the tagged commit [92e52d7](https://github.com/RohitKushvaha01/Xed-Editor/commit/92e52d71d371cfca346b9a759579663922f03a87).

Thank you for your understanding and patience.

**Comment by linsui** [comment]
It failed again. Please rebuild the apk from the tag.

**Comment by RohitKushvaha01** [comment]
> It failed again. Please rebuild the apk from the tag.

assuming your are talking about v2.2.0 i updated the apk

**Comment by linsui** [comment]
2.3.0 reproducible build failed.

**Comment by RohitKushvaha01** [comment]
> 2.3.0 reproducible build failed.

i updated the apk

**Comment by linsui** [comment]
Fixed, thanks!
