### ISSUE TITLE
https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#g-submitting-notices


### ISSUE THREAD

**Issue by spunkanator** [RohitKushvaha01/Xed-Editor#81]
https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#g-submitting-notices

**Comment by RohitKushvaha01** [comment]
> https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#g-submitting-notices

@spunkanator what you want to say? with this link

**Comment by AndroMaster436** [comment]
> > https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#g-submitting-notices
> 
> @spunkanator what you want to say? with this link

I think he wants to throw copyright on this repository
