### ISSUE TITLE
Feedback/Testing 2.6

### ISSUE THREAD

**Issue by Raffa064** [RohitKushvaha01/Xed-Editor#82]
All the tests has been done with the release apk v2.6. I didn't encounter any of the crashes I had previously reported, but I've found some new problems, all described below.

## Bugs/Crashs
- [x]  I've found a crash when clickad at "Open with" option from file popup menu, the logs can be found [here](https://github.com/user-attachments/files/16632219/logs.txt)

- [x] I don't know how to explain this... too much icons at the action bar makes the three dots menu go outside the screen...
![IMG_20240815_234101](https://github.com/user-attachments/assets/829e89d1-cbb6-440d-a30d-5b9673a28010)

- [x]  Close search button has threw an error, but it occurs just once time. I didn't know why. [here is the logs](https://github.com/user-attachments/files/16632321/logs.txt)

- [x] Empty search cause this [error](https://github.com/user-attachments/files/16632335/logs.txt)

- [x] This [error](https://github.com/user-attachments/files/16632365/logs.txt)
 occurs when I tried clicked "go to next match" button, after changed to another file (other than the one I've started the search)

- [x]  "Insert Date" isn't added to the history, so it can't be undone

## Suggestions / Minor issues
- There was a little delay when opening files, even when the file was small:

![IMG_20240815_231559](https://github.com/user-attachments/assets/13f29399-78a2-4ec4-a5e2-c28c31dd8476)

- [x]  I think it would be better to have an option to disable that cursor "animation", which becomes kind of "floating" when you change its position:

![km_20240815_360p_12f_20240815_230853](https://github.com/user-attachments/assets/40ce7d25-eb9a-4c6e-9148-170a48f8498d)
- [x]  It would be more intuitive if plugins had their own section instead of being placed inside "Applications", and the option to activate and deactivate them could be there inside that section.
![IMG_20240815_231050](https://github.com/user-attachments/assets/eae0a336-a40d-44e7-873c-0a2659fa5f29)

- [x]  The first latter of "File saved" toast is in lower case, that's not a big issue
- [x]  The clipboard empty toast is missing a space between the words:
![IMG_20240815_233627](https://github.com/user-attachments/assets/29c8925a-052e-456b-b3e8-9fdb42e34edf)

- I don't know if it's possible, but you can add an color picker instead of a list of themes, allowing the user to use whatever color he wants to.

- [x] A common editor option that's missing, is the tab/space toggler.

- [x] Extra keys paddings is too large:
![IMG_20240815_232428](https://github.com/user-attachments/assets/33ae3be5-938f-4741-bd46-62ac263c0013)

- What is Diagnol Scrolling? I didn't see any difference by enabling this...
![IMG_20240815_232652](https://github.com/user-attachments/assets/12c4bf79-9cbf-45c9-bc61-cb9f70a8b4f0)

- [x] File Browser three dots New Folder Option doesn't autorefresh after creating the folder.

**Comment by AndroMaster436** [comment]
> All the tests has been done with the release apk v2.6. I didn't encounter any of the crashes I had previously reported, but I've found some new problems, all described below.
> 
> ## Bugs/Crashs
> * I've found a crash when clickad at "Open with" option from file popup menu, the logs can be found [here](https://github.com/user-attachments/files/16632219/logs.txt)
> * I don't know how to explain this... too much icons at the action bar makes the three dots menu go outside the screen...
>   ![IMG_20240815_234101](https://private-user-images.githubusercontent.com/124680730/358451675-829e89d1-cbb6-440d-a30d-5b9673a28010.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDUxNjc1LTgyOWU4OWQxLWNiYjYtNDQwZC1hMzBkLTViOTY3M2EyODAxMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGM5NmY4YzM0ZGQwMGM4NjljYzZjZTIxZmEyNzU5OTc4YWVjODE2NTI3ZTFhMDdjNmZmZmQxZjJiMmY0YWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xb4JNy-41BRZUJB9GYHCxoXw-ciCVQwXhgqSn3r8HMc)
> * Close search button has threw an error, but it occurs just once time. I didn't know why. [here is the logs](https://github.com/user-attachments/files/16632321/logs.txt)
> * Empty search cause this [error](https://github.com/user-attachments/files/16632335/logs.txt)
> * This [error](https://github.com/user-attachments/files/16632365/logs.txt)
>   occurs when I tried clicked "go to next match" button, after changed to another file (other than the one I've started the search)
> * "Insert Date" isn't added to the history, so it can't be undone
> 
> ## Suggestions / Minor issues
> * There was a little delay when opening files, even when the file was small:
> 
> ![IMG_20240815_231559](https://private-user-images.githubusercontent.com/124680730/358447720-13f29399-78a2-4ec4-a5e2-c28c31dd8476.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ3NzIwLTEzZjI5Mzk5LTc4YTItNGVjNC1hNWUyLWMyOGMzMWRkODQ3Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2Y5YzEwM2FjMWNhNWNhOGUyN2M5OTIzY2RlZDMxZGM3YjY0ODJhOWFiMmU4NWU4M2ZiZTk1MjlhODUwNmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SMzng55G33bls5dX0R1Fk9VX4EZSd79aUHkeDLZ6KyM)
> 
> * I think it would be better to have an option to disable that cursor "animation", which becomes kind of "floating" when you change its position:
> 
> ![km_20240815_360p_12f_20240815_230853](https://private-user-images.githubusercontent.com/124680730/358446792-40ce7d25-eb9a-4c6e-9148-170a48f8498d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ2NzkyLTQwY2U3ZDI1LWViOWEtNGM2ZS05MTQ4LTE3MGE0OGY4NDk4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVlMmMyMWE3MTg3OWE4ODNiNDE1NzJiYmJmOGU3MzY1NWE5M2FmODhjMDUyYjNlNGNlMGU4MzliZDhkOGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.myvlKPTuqVunhHM0zKXbKGGuA8y4IK18axLrI1FHJKo) [ ![km_20240815_360p_12f_20240815_230853](https://private-user-images.githubusercontent.com/124680730/358446792-40ce7d25-eb9a-4c6e-9148-170a48f8498d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ2NzkyLTQwY2U3ZDI1LWViOWEtNGM2ZS05MTQ4LTE3MGE0OGY4NDk4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVlMmMyMWE3MTg3OWE4ODNiNDE1NzJiYmJmOGU3MzY1NWE5M2FmODhjMDUyYjNlNGNlMGU4MzliZDhkOGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.myvlKPTuqVunhHM0zKXbKGGuA8y4IK18axLrI1FHJKo) ](https://private-user-images.githubusercontent.com/124680730/358446792-40ce7d25-eb9a-4c6e-9148-170a48f8498d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ2NzkyLTQwY2U3ZDI1LWViOWEtNGM2ZS05MTQ4LTE3MGE0OGY4NDk4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVlMmMyMWE3MTg3OWE4ODNiNDE1NzJiYmJmOGU3MzY1NWE5M2FmODhjMDUyYjNlNGNlMGU4MzliZDhkOGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.myvlKPTuqVunhHM0zKXbKGGuA8y4IK18axLrI1FHJKo) [ ](https://private-user-images.githubusercontent.com/124680730/358446792-40ce7d25-eb9a-4c6e-9148-170a48f8498d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ2NzkyLTQwY2U3ZDI1LWViOWEtNGM2ZS05MTQ4LTE3MGE0OGY4NDk4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVlMmMyMWE3MTg3OWE4ODNiNDE1NzJiYmJmOGU3MzY1NWE5M2FmODhjMDUyYjNlNGNlMGU4MzliZDhkOGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.myvlKPTuqVunhHM0zKXbKGGuA8y4IK18axLrI1FHJKo)
> 
> * It would be more intuitive if plugins had their own section instead of being placed inside "Applications", and the option to activate and deactivate them could be there inside that section.
>   ![IMG_20240815_231050](https://private-user-images.githubusercontent.com/124680730/358447176-eae0a336-a40d-44e7-873c-0a2659fa5f29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ3MTc2LWVhZTBhMzM2LWE0MGQtNDRlNy04NzNjLTBhMjY1OWZhNWYyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGI3YTQ0Y2FkN2ExNDMzODRlZDQ0MGRmYjE1ZTFmZDUyZDRkZTExOWJjZjhhZDlmOTJmMGE3NWQ5ZGY2MGY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dPNs1LLy2lG9xxBPGBt7rMOtIz_00fSmYr89zs7AmLs)
> * The first latter of "File saved" toast is in lower case, that's not a big issue
> * The clipboard empty toast is missing a space between the words:
>   ![IMG_20240815_233627](https://private-user-images.githubusercontent.com/124680730/358450901-29c8925a-052e-456b-b3e8-9fdb42e34edf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDUwOTAxLTI5Yzg5MjVhLTA1MmUtNDU2Yi1iM2U4LTlmZGI0MmUzNGVkZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDViMDMyNjBmZWExZDYyNDgzOGU0ODFmODY0YWQyMjgxNWJmMzVjZWFhNTcyM2FhNzI4M2IwYjUxZTkwMDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X9tD3jeYZ97-BGH6rYhKuoBRrsYfNa2M1tgmVURBYko)
> * I don't know if it's possible, but you can add an color picker instead of a list of themes, allowing the user to use whatever color he wants to.
> * A common editor option that's missing, is the tab/space toggler.
> * Extra keys paddings is too large:
>   ![IMG_20240815_232428](https://private-user-images.githubusercontent.com/124680730/358448922-33ae3be5-938f-4741-bd46-62ac263c0013.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ4OTIyLTMzYWUzYmU1LTkzOGYtNDc0MS1iZDQ2LTYyYWMyNjNjMDAxMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTE2OTEyODM0MzQ0NDgyOGRjMGNjZGQyOTc2YzA4NTMyMjRjMGFjODg4NDMwZGU0YzMzZTFkNjU1YTk4NGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mKLnxPl0oUeu8j416C2B_mjajVZPdsbaQIjr_nbkgI8)
> * What is Diagnol Scrolling? I didn't see any difference by enabling this...
>   ![IMG_20240815_232652](https://private-user-images.githubusercontent.com/124680730/358449265-12c4bf79-9cbf-45c9-bc61-cb9f70a8b4f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODMxMTEsIm5iZiI6MTcyMzc4MjgxMSwicGF0aCI6Ii8xMjQ2ODA3MzAvMzU4NDQ5MjY1LTEyYzRiZjc5LTljYmYtNDVjOS1iYzYxLWNiOWY3MGE4YjRmMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWI0MTFjZTNjYTZlOGNmNzZmMzI4NTYyNjFmNWY4ZTg2YjllM2ZhMWI2Zjg4ODkxMmMwNzEzZTQ1ZGRhNjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Etnzr2xmb-sYkIIhhD5C6L_EKuXeoC5gIGo_F7cF2-c)
> * File Browser three dots New Folder Option doesn't autorefresh after creating the folder.

Regarding diagonal scrolling in the file tree:

off: You can only scroll through files if you swipe from the file/folder name
on: you can swipe from empty space

Although sometimes the names of folders/files are very short (personally, I have) and swiping on the names to scroll is not very convenient. I think that diagonal scrolling should be enabled by default

**Comment by RohitKushvaha01** [comment]
@Raffa064 

"There was a little delay when opening files, even when the file was small:"

this only happens when you open a file for the first time because the editor has to lead syntax highlighting

**Comment by AndroMaster436** [comment]
> @Raffa064
> 
> "There was a little delay when opening files, even when the file was small:"
> 
> this only happens when you open a file for the first time because the editor has to load syntax highlighting

For some reason, I have a micro delay every time I open a file. Moreover, if you look at the code, you can understand that the delay is fake (like time.sleep() in python)
I understand that this is done so that all components load without problems, but the idea of implementation itself is somehow strange 0_о
