### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by osbyrne** [RohitKushvaha01/Xed-Editor#84]
Fatal Crash occurred on Thread named 'Thread-7'
Unix Time : 1723925634279
LocalTime : Aug 17, 2024 22:13:54

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = Redmi Note 7
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2021-10-01
BASE_OS = 
RELEASE = 10
CODENAME = REL
manufacturer = Xiaomi
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 28
PREVIEW_SDK_INT = 0
SDK = 29
brand = xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V12.5.3.0.QFGMIXM

Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:919)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-7' Unix Time : 1723925634279 LocalTime : Aug 17, 2024 22:13:54
> 
> ACTIVE_CODENAMES = [] app_version = 2.6.0 device_model = Redmi Note 7 RESOURCES_SDK_INT = 29 SECURITY_PATCH = 2021-10-01 BASE_OS = RELEASE = 10 CODENAME = REL manufacturer = Xiaomi SDK_INT = 29 PREVIEW_SDK_FINGERPRINT = REL FIRST_SDK_INT = 28 PREVIEW_SDK_INT = 0 SDK = 29 brand = xiaomi supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = V12.5.3.0.QFGMIXM
> 
> Error Message : listFiles(...) must not be null Error Cause : null Error StackTrace :
> 
> java.lang.NullPointerException: listFiles(...) must not be null at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214) at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35) at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0) at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) at java.lang.Thread.run(Thread.java:919)

What path you are trying to access?
accessing /sdcard/Android or /storage/emulated/0/Android is not allowed by android os and if you try it will throw this exception

**Comment by osbyrne** [comment]
feels weird trying to open a folder and having a core dump show up - maybe a "android doesn't allow going on this path" and a button to go back would make more sense
