### ISSUE TITLE
Folders list

### ISSUE THREAD

**Issue by AndroMaster436** [RohitKushvaha01/Xed-Editor#91]
**Is your feature request related to a problem? Please describe.**
It is very inconvenient that when you want to open another folder, you have to close the folder and find the desired folder through Explorer

**Describe the solution you'd like**
![Screenshot_20240820-112118~3](https://github.com/user-attachments/assets/09cf7eaf-cec7-4743-8065-8f46965c8391)
So that the specified line is clickable and you can add folders there that you often visit (you can move the ability to open private files there (if you want)). When you click on the desired folder, it will open immediately. This will be very convenient for several projects

**Additional context**
So that you can also add folders from a remote host (when Sftp will be done)

**Comment by AndroMaster436** [comment]
![Screenshot_20240828-150229~3](https://github.com/user-attachments/assets/311410b8-b12c-460a-b224-72918e341ffb)
It seems to be almost ready, but perhaps it is not convenient that when opening a project you also need to click on the folder with the project (yes, I know that it is needed so that it can be closed) Therefore, 3 dots can be used as an alternative (I'm just suggesting my solution and not insisting that it be mandatory)

**Comment by RohitKushvaha01** [comment]
> And it doesn't save open projects!

It's not complete yet

**Comment by AndroMaster436** [comment]
Now successfully saving
What else are you going to do about it? Or can I close issue?
