### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Raffa064** [RohitKushvaha01/Xed-Editor#94]
**NOTE:** I'm testing the last debug version, from commit [7c61689](https://github.com/RohitKushvaha01/Xed-Editor/commit/7c616890c0abff39201dc04d75710d86d14c3411)

Fatal Crash occurred on Thread named 'Thread-3'
Unix Time : 1724321892283
LocalTime : Aug 22, 2024 07:18:12

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = POCOPHONE F1
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2020-12-01
BASE_OS = 
RELEASE = 10
CODENAME = REL
manufacturer = Xiaomi
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 27
PREVIEW_SDK_INT = 0
SDK = 29
brand = Xiaomi
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = V12.0.3.0.QEJMIXM

Error Message : java.lang.String cannot be cast to java.lang.Boolean
Error Cause : null
Error StackTrace : 

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:331)
	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:55)
	at com.rk.xededitor.App.onCreate$lambda$0(App.kt:30)
	at com.rk.xededitor.App.$r8$lambda$q4_rjLPY7otD0GqEKHZVklTaV5Y(Unknown Source:0)
	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at com.rk.libcommons.After._init_$lambda$0(After.kt:10)
	at com.rk.libcommons.After.$r8$lambda$GXVDRHX2mO51FLSlE20TBz-vSbM(Unknown Source:0)
	at com.rk.libcommons.After$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:919)

**Comment by RohitKushvaha01** [comment]
> **NOTE:** I'm testing the last debug version, from commit [7c61689](https://github.com/RohitKushvaha01/Xed-Editor/commit/7c616890c0abff39201dc04d75710d86d14c3411)
> 
> Fatal Crash occurred on Thread named 'Thread-3'
> Unix Time : 1724321892283
> LocalTime : Aug 22, 2024 07:18:12
> 
> ACTIVE_CODENAMES = []
> app_version = 2.6.0
> device_model = POCOPHONE F1
> RESOURCES_SDK_INT = 29
> SECURITY_PATCH = 2020-12-01
> BASE_OS = 
> RELEASE = 10
> CODENAME = REL
> manufacturer = Xiaomi
> SDK_INT = 29
> PREVIEW_SDK_FINGERPRINT = REL
> FIRST_SDK_INT = 27
> PREVIEW_SDK_INT = 0
> SDK = 29
> brand = Xiaomi
> supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
> INCREMENTAL = V12.0.3.0.QEJMIXM
> 
> 
> Error Message : java.lang.String cannot be cast to java.lang.Boolean
> Error Cause : null
> Error StackTrace : 
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:331)
> 	at com.rk.xededitor.Settings.SettingsData.getBoolean(SettingsData.kt:55)
> 	at com.rk.xededitor.App.onCreate$lambda$0(App.kt:30)
> 	at com.rk.xededitor.App.$r8$lambda$q4_rjLPY7otD0GqEKHZVklTaV5Y(Unknown Source:0)
> 	at com.rk.xededitor.App$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at com.rk.libcommons.After._init_$lambda$0(After.kt:10)
> 	at com.rk.libcommons.After.$r8$lambda$GXVDRHX2mO51FLSlE20TBz-vSbM(Unknown Source:0)
> 	at com.rk.libcommons.After$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
> 	at java.lang.Thread.run(Thread.java:919)
> 

the crash occurred because the SettingsData.kt class was refactored, and now certain settings require different data types than before. The error you're seeing indicates that the app is trying to cast a String to a Boolean, which is causing the crash.To resolve this, you should clear the app data. This will reset the settings to their default values, allowing the app to function correctly with the updated SettingsData class.

**Comment by Raffa064** [comment]
Ok, It works now. I din't found any of the last errors I've reported before. 😎👍

**Problems i've found at this version:**
- For some reason, the arrow keys of search mode are inverted.
- Unsaved files might alert when you close them (Close this/all/others)
- That "diagonal scrolling" option still having a typo in the name: *Diagnol*
