### ISSUE TITLE
File content erased!

### ISSUE THREAD

**Issue by AndroMaster436** [RohitKushvaha01/Xed-Editor#95]
**Describe the bug**
I go into the editor (it was hanging in the background), it crashed. I open the file that was open - it is empty. I checked in the file manager - the file is empty :(

**To Reproduce**
1. Exit from app (do not close in background)
2. Open another apps and wait some time
3. Open Karbon again

**Expected behavior**
File content does not erased

**Screenshots**
![Screenshot_20240822-200403](https://github.com/user-attachments/assets/4168edde-c005-4ae5-96d0-7acaa2b9f15d)

**complete the following information):**
 - Device: Redmi 10
 - OS: Pixel Experience
 - Android Version: 11

**Comment by RohitKushvaha01** [comment]
> **Describe the bug**
> I go into the editor (it was hanging in the background), it crashed. I open the file that was open - it is empty. I checked in the file manager - the file is empty :(
> 
> **To Reproduce**
> 1. Exit from app (do not close in background)
> 2. Open another apps and wait some time
> 3. Open Karbon again
> 
> **Expected behavior**
> File content does not erased
> 
> **Screenshots**
> ![Screenshot_20240822-200403](https://github.com/user-attachments/assets/4168edde-c005-4ae5-96d0-7acaa2b9f15d)
> 
> **complete the following information):**
>  - Device: Redmi 10
>  - OS: Pixel Experience
>  - Android Version: 11

This issue likely occurred due to the auto-save feature, which might have overwritten the file contents while the app was running in the background. It's important to keep backups of important files to avoid data loss in such cases. I hope you had a backup of your file.

**Comment by AndroMaster436** [comment]
> > **Describe the bug**
> > I go into the editor (it was hanging in the background), it crashed. I open the file that was open - it is empty. I checked in the file manager - the file is empty :(
> > **To Reproduce**
> > 
> > 1. Exit from app (do not close in background)
> > 2. Open another apps and wait some time
> > 3. Open Karbon again
> > 
> > **Expected behavior**
> > File content does not erased
> > **Screenshots**
> > ![Screenshot_20240822-200403](https://private-user-images.githubusercontent.com/87223939/360564453-4168edde-c005-4ae5-96d0-7acaa2b9f15d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODQ0NjcsIm5iZiI6MTcyNDM4NDE2NywicGF0aCI6Ii84NzIyMzkzOS8zNjA1NjQ0NTMtNDE2OGVkZGUtYzAwNS00YWU1LTk2ZDAtN2FjYWEyYjlmMTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTYxMzAwNzZiMTA3ZjUxZDA1YzkzYTdhMjFiN2EzZjMyNWIwY2MzYjRkODY4ZTFmNjFlNWFhMTM0ZGNmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XEdzvRq25WseT3KXv3e0MD7EkRhIbNA9PjpnjnkXS64)
> > **complete the following information):**
> > 
> > * Device: Redmi 10
> > * OS: Pixel Experience
> > * Android Version: 11
> 
> This issue likely occurred due to the auto-save feature, which might have overwritten the file contents while the app was running in the background. It's important to keep backups of important files to avoid data loss in such cases. I hope you had a backup of your file.

I restored it from GitHub

**Comment by AndroMaster436** [comment]
Fixed?

**Comment by RohitKushvaha01** [comment]
> Fixed?

yes
