### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by bettachini** [RohitKushvaha01/Xed-Editor#96]
Fatal Crash occurred on Thread named 'Thread-46'
Unix Time : 1724413629427
LocalTime : 23 Aug 2024 08:47:09

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = 5102B
RESOURCES_SDK_INT = 29
SECURITY_PATCH = 2023-01-05
BASE_OS = TCL/5102B/Seoul:10/QKQ1.200623.002/v3CEH-0:user/release-keys
RELEASE = 10
CODENAME = REL
manufacturer = TCL
SDK_INT = 29
PREVIEW_SDK_FINGERPRINT = REL
FIRST_SDK_INT = 29
PREVIEW_SDK_INT = 0
SDK = 29
brand = TCL
supported_abi = [armeabi-v7a,armeabi]
INCREMENTAL = v3EAC-0

Error Message : /storage/home/findOut.md: open failed: ENOENT (No such file or directory)
Error Cause : android.system.ErrnoException: open failed: ENOENT (No such file or directory)
Error StackTrace : 

java.io.FileNotFoundException: /storage/home/findOut.md: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at com.rk.xededitor.MainActivity.MenuClickHandler$Companion.saveFile$lambda$2(MenuClickHandler.kt:253)
	at com.rk.xededitor.MainActivity.MenuClickHandler$Companion.$r8$lambda$zQdLnpc7EKgCAa39Mb0hLqAt2JA(Unknown Source:0)
	at com.rk.xededitor.MainActivity.MenuClickHandler$Companion$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7398)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 5 more

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-46' Unix Time : 1724413629427 LocalTime : 23 Aug 2024 08:47:09
> 
> ACTIVE_CODENAMES = [] app_version = 2.6.0 device_model = 5102B RESOURCES_SDK_INT = 29 SECURITY_PATCH = 2023-01-05 BASE_OS = TCL/5102B/Seoul:10/QKQ1.200623.002/v3CEH-0:user/release-keys RELEASE = 10 CODENAME = REL manufacturer = TCL SDK_INT = 29 PREVIEW_SDK_FINGERPRINT = REL FIRST_SDK_INT = 29 PREVIEW_SDK_INT = 0 SDK = 29 brand = TCL supported_abi = [armeabi-v7a,armeabi] INCREMENTAL = v3EAC-0
> 
> Error Message : /storage/home/findOut.md: open failed: ENOENT (No such file or directory) Error Cause : android.system.ErrnoException: open failed: ENOENT (No such file or directory) Error StackTrace :
> 
> java.io.FileNotFoundException: /storage/home/findOut.md: open failed: ENOENT (No such file or directory) at libcore.io.IoBridge.open(IoBridge.java:496) at java.io.FileOutputStream.(FileOutputStream.java:235) at com.rk.xededitor.MainActivity.MenuClickHandler$Companion.saveFile$lambda$2(MenuClickHandler.kt:253) at com.rk.xededitor.MainActivity.MenuClickHandler$Companion.$r8$lambda$zQdLnpc7EKgCAa39Mb0hLqAt2JA(Unknown Source:0) at com.rk.xededitor.MainActivity.MenuClickHandler$Companion$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0) at java.lang.Thread.run(Thread.java:919) Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory) at libcore.io.Linux.open(Native Method) at libcore.io.ForwardingOs.open(ForwardingOs.java:167) at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252) at libcore.io.ForwardingOs.open(ForwardingOs.java:167) at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7398) at libcore.io.IoBridge.open(IoBridge.java:482) ... 5 more

you are trying to modify a file that no longer exists, it may be deleted by other apps
