### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by 0453001** [RohitKushvaha01/Xed-Editor#98]
Fatal Crash occurred on Thread named 'Thread-7'
Unix Time : 1724456165348
LocalTime : 23 ago 2024 20:36:05

ACTIVE_CODENAMES = []
app_version = 2.6.0
device_model = SM-A035M
SEM_INT = 3301
SECURITY_PATCH = 2024-03-01
BASE_OS = samsung/a03ub/a03:13/TP1A.220624.014/A035MUBU5CWK1:user/release-keys
SEM_FIRST_SDK_INT = 30
RELEASE = 13
MEDIA_PERFORMANCE_CLASS = 0
CODENAME = REL
manufacturer = samsung
RELEASE_OR_CODENAME = 13
RELEASE_OR_PREVIEW_DISPLAY = 13
KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}
SDK_INT = 33
PREVIEW_SDK_FINGERPRINT = REL
PREVIEW_SDK_INT = 0
SDK = 33
SEM_PLATFORM_INT = 140100
brand = samsung
supported_abi = [arm64-v8a,armeabi-v7a,armeabi]
INCREMENTAL = A035MUBS6CXC1

Error Message : listFiles(...) must not be null
Error Cause : null
Error StackTrace : 

java.lang.NullPointerException: listFiles(...) must not be null
	at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214)
	at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35)
	at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0)
	at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by RohitKushvaha01** [comment]
> Fatal Crash occurred on Thread named 'Thread-7' Unix Time : 1724456165348 LocalTime : 23 ago 2024 20:36:05
> 
> ACTIVE_CODENAMES = [] app_version = 2.6.0 device_model = SM-A035M SEM_INT = 3301 SECURITY_PATCH = 2024-03-01 BASE_OS = samsung/a03ub/a03:13/TP1A.220624.014/A035MUBU5CWK1:user/release-keys SEM_FIRST_SDK_INT = 30 RELEASE = 13 MEDIA_PERFORMANCE_CLASS = 0 CODENAME = REL manufacturer = samsung RELEASE_OR_CODENAME = 13 RELEASE_OR_PREVIEW_DISPLAY = 13 KNOWN_CODENAMES = {HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair} SDK_INT = 33 PREVIEW_SDK_FINGERPRINT = REL PREVIEW_SDK_INT = 0 SDK = 33 SEM_PLATFORM_INT = 140100 brand = samsung supported_abi = [arm64-v8a,armeabi-v7a,armeabi] INCREMENTAL = A035MUBS6CXC1
> 
> Error Message : listFiles(...) must not be null Error Cause : null Error StackTrace :
> 
> java.lang.NullPointerException: listFiles(...) must not be null at com.rk.xededitor.MainActivity.treeview2.TreeViewAdapter$Companion.merge(TreeViewAdapter.kt:214) at com.rk.xededitor.MainActivity.treeview2.TreeView._init_$lambda$3(TreeView.kt:35) at com.rk.xededitor.MainActivity.treeview2.TreeView.$r8$lambda$JBvSDOOqbKRJBQ0KIXzLdcjWoLM(Unknown Source:0) at com.rk.xededitor.MainActivity.treeview2.TreeView$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) at java.lang.Thread.run(Thread.java:1012)

this crash is already fixed in action builds, you are using release build or fdroid

you can wait for next release or you can download latest commit build from github actions
